### ISSUE TITLE
Invalid Checksum on MacOS when downloading Kubernetes

### ISSUE THREAD

**Issue by ntarorabv** [rancher-sandbox/rancher-desktop#1242]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

macOS

### Operating System / Build Version

macOS BugSur 11.6.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Actual Behavior

After multiple attempts when RD tries to download the k3 images it fails on checksum validation.

```
There was an unknown error starting Kubernetes: Error: k3s-airgap-images-arm64.tar has invalid digest 4d448509b176f7ba34119564bb459a29e6cc6493c6fafe5ed85b2d070de9f428, expected dbac528c4699e21f87a8ba086925ab137396e26dfefe7d2f205e9e29851e1c7d
```

### Steps to Reproduce

Download RD 0.7.1 - Start up and see error after k8 download.

Also tested on 0.7.0 with similar results.

### Result

Here are logs from two attempts. Notice the checksum RD calculates is different both times as well.
```
2022-01-13T18:35:03.965Z: Error verifying checksums after download Error: k3s-airgap-images-arm64.tar has invalid digest 3ee270c5022b69768e285225021e009857a6b2e873258beb480128548a116410, expected dbac528c4699e21f87a8ba086925ab137396e26dfefe7d2f205e9e29851e1c7d
    at /private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:21293
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async r (/private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:21367)
    at async Tt.ensureK3sImages (/private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:22103)
2022-01-13T18:47:27.435Z: Ensuring images available for K3s 1.22.5
2022-01-13T18:47:27.588Z: Will download exe https://github.com/k3s-io/k3s/releases/download/v1.22.5+k3s1/k3s-arm64 to /Users/neelarora/Library/Caches/rancher-desktop/k3s/tmp-v1.22.5+k3s1-pKbaUJ/k3s-arm64
2022-01-13T18:47:27.593Z: Will download images https://github.com/k3s-io/k3s/releases/download/v1.22.5+k3s1/k3s-airgap-images-arm64.tar to /Users/neelarora/Library/Caches/rancher-desktop/k3s/tmp-v1.22.5+k3s1-pKbaUJ/k3s-airgap-images-arm64.tar
2022-01-13T18:47:27.594Z: Will download checksum https://github.com/k3s-io/k3s/releases/download/v1.22.5+k3s1/sha256sum-arm64.txt to /Users/neelarora/Library/Caches/rancher-desktop/k3s/tmp-v1.22.5+k3s1-pKbaUJ/sha256sum-arm64.txt
2022-01-13T18:48:30.386Z: Error verifying checksums after download Error: k3s-airgap-images-arm64.tar has invalid digest 4d448509b176f7ba34119564bb459a29e6cc6493c6fafe5ed85b2d070de9f428, expected dbac528c4699e21f87a8ba086925ab137396e26dfefe7d2f205e9e29851e1c7d
    at /private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:21293
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async r (/private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:21367)
    at async Tt.ensureK3sImages (/private/var/folders/rj/f3dk9d2555vdj_vk71gpftfw0000gq/T/AppTranslocation/F2AFFD92-2F63-4937-AD68-62CCE0C82731/d/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:22103)
```

### Expected Behavior

k8 is downloaded and validated with the correct checksum

**Comment by mook-as** [comment]
Hmm, I manually downloaded [k3s 1.22.5+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.22.5%2Bk3s1), and the checksums are as expected (`dbac528c4699e21f87a8ba086925ab137396e26dfefe7d2f205e9e29851e1c7d`).  Does trying again work for you? I wonder if GitHub had an intermittent issue and gave you a bad download (`3ee270c5022b69768e285225021e009857a6b2e873258beb480128548a116410`).

I also suspect we should at least be using the gzip version instead, though of course the zstd version would be even smaller (but I'm not sure it'd be easy for us to extract)…

**Comment by ntarorabv** [comment]
I am going to close this out for now. It looks like there might be something happening to my network traffic causing this as I started seeing more checksum errors in other areas today.
