### ISSUE TITLE
Error installing Rancher Desktop "Can't get version for kubectl"

### ISSUE THREAD

**Issue by kobo-gcyre** [rancher-sandbox/rancher-desktop#1244]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.21.8

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur 11.6.2

### What CPU architecture are you using?

x64

### Actual Behavior

After selecting the K8S version installation fails with error

There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255

background.log has an error
```���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������2022-01-13T22:26:13.455Z: Trying to determine version, can't get output from /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl version Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  stdout: ''
}
2022-01-13T22:26:13.456Z: Can't get version for kubectl in /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
2022-01-13T22:34:39.690Z: UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)
2022-01-13T22:36:06.608Z: UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)```

I saw an error in a different log file that showed a 404 error calling `googleapis` 
Error from k8s.log

```I0113 17:44:41.160301   65095 versioner.go:84] Right kubectl missing, downloading version 1.13.4
F0113 17:44:41.634132   65095 main.go:69] Error while trying to get contents of https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/darwin/amd64/kubectl.sha256: GET https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/darwin/amd64/kubectl.sha256 returned http status 404 Not Found
```

### Steps to Reproduce

Download 0.7.1
extract .app 
copy to Application folder
run Rancher Desktop

### Result

```There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255```

### Expected Behavior

installs and runs k3s?

**Comment by micxer** [comment]
I just experienced this with 1.0.0 as well, but it asks for an even older version:

```
==> k8s.log <==
2022-01-31T13:12:46.862Z: Updating kubeconfig /Users/micxer/.kube/config...
2022-01-31T13:12:46.943Z: Setting default context...
I0131 14:12:47.998171   18346 versioner.go:84] Right kubectl missing, downloading version 1.11.0+d4cacc0
F0131 14:12:48.319899   18346 main.go:69] Error while trying to get contents of https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/darwin/amd64/kubectl.sha256: GET https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/darwin/amd64/kubectl.sha256 returned http status 404 Not Found

==> lima.log <==
2022-01-31T13:12:48.323Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

==> background.log <==
2022-01-31T13:12:48.328Z: Kubernetes was unable to start: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by mrbradleylee** [comment]
Also getting this in 1.0.1, specifically on OS X Monterey, M1, so `arm64`. 
I do have an existing context configured for GKE, if that matters/helps.

My logs:

### k8s
```
2022-02-03T17:51:41.054Z: Waiting for K3s server to be ready on port 6443...
2022-02-03T17:51:41.068Z: Error: connect ECONNREFUSED 127.0.0.1:6443
2022-02-03T17:51:42.467Z: Updating kubeconfig /Users/skeletor/.kube/config...
2022-02-03T17:51:42.506Z: Setting default context...
I0203 10:51:42.936438   99820 versioner.go:58] no Auth Provider found for name "gcp"
I0203 10:51:42.961181   99820 versioner.go:64] No local kubectl binary found, fetching latest stable release version
F0203 10:52:12.969500   99820 main.go:62] Get https://storage.googleapis.com/kubernetes-release/release/stable.txt: dial tcp: i/o timeout
```

### background.log
```
2022-02-03T17:51:08.028Z: Expected error moving Lima state: Error: ENOENT: no such file or directory, rename '/Users/skeletor/Library/State/rancher-desktop/lima' -> '/Users/skeletor/Library/Application Support/rancher-desktop/lima'
2022-02-03T17:51:11.305Z: event settings-read in main: [object Object]
2022-02-03T17:52:12.989Z: Kubernetes was unable to start: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
2022-02-03T18:42:02.257Z: UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)
2022-02-03T18:42:05.811Z: event settings-read in main: [object Object]
2022-02-03T18:42:09.800Z: event settings-read in main: [object Object]
2022-02-03T18:42:11.018Z: event settings-read in main: [object Object]
2022-02-03T18:42:12.132Z: event settings-read in main: [object Object]
2022-02-03T18:42:39.672Z: Trying to determine version, can't get output from /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl version Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 255
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8656)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: ''
}
2022-02-03T18:42:39.675Z: Can't get version for kubectl in /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl
```

**Comment by max-wittig** [comment]
Same issue here since upgrading to 1.0.1. Sadly downgrading back to 1.0.0 didn't fix the problem

**Comment by max-wittig** [comment]
Completely wiping every since config (e.g. with AppCleaner) and reinstalling 1.0.0 seems to help.

Maybe it has something to do with selecting `moby` at the setup phase? (After update)

**Comment by jandubois** [comment]
This is not reproducible by me; please re-open if this still happens with RD 1.4.1.

We are aware that `kubectl version` displays some noise when it cannot connect to a cluster, but that is a separate issue and does not prevent RD from starting.
