### ISSUE TITLE
Error Starting Kubernetes

### ISSUE THREAD

**Issue by rickytillis** [rancher-sandbox/rancher-desktop#1287]
### Rancher Desktop Version

0.7.1

### Rancher Desktop K8s Version

1.22.5

### What operating system are you using?

macOS

### Operating System / Build Version

Big Sur

### What CPU architecture are you using?

x64

### Actual Behavior

There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

Docker commands not working:

#docker run hello-world                                                                   
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

### Steps to Reproduce

Fresh install of Rancher, or reset Kubernetes. Seems to fail on starting virtual machine.

### Result

There was an unknown error starting Kubernetes: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1

### Expected Behavior

No error and Docker commands to work

### Additional Information

I have tried methods mentioned on support page with same error but nothing is working.

lima.log
time="2022-01-20T08:31:50-05:00" level=info msg="The QEMU process seems already stopped"
time="2022-01-20T08:31:50-05:00" level=info msg="The host agent process seems already stopped"
time="2022-01-20T08:31:50-05:00" level=info msg="Removing *.pid *.sock under \"/Users/rtillis/Library/Application Support/rancher-desktop/lima/0\""
time="2022-01-20T08:31:50-05:00" level=info msg="Deleted \"0\" (\"/Users/rtillis/Library/Application Support/rancher-desktop/lima/0\")"
"/private/etc/sudoers.d/rancher-desktop-lima" is up-to-date (or sudo doesn't require a password)
time="2022-01-20T08:32:11-05:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-01-20T08:32:11-05:00" level=info msg="Starting switch daemon for \"bridged_en10\" network"
time="2022-01-20T08:32:11-05:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-01-20T13:32:11.671Z: + limactl start --tty=false /Users/rtillis/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-01-20T13:32:11.673Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-01-20T13:32:11.673Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
time="2022-01-20T08:34:16-05:00" level=info msg="The QEMU process seems already stopped"
time="2022-01-20T08:34:16-05:00" level=info msg="The host agent process seems already stopped"
time="2022-01-20T08:34:16-05:00" level=info msg="Removing *.pid *.sock under \"/Users/rtillis/Library/Application Support/rancher-desktop/lima/0\""
time="2022-01-20T08:34:16-05:00" level=info msg="Deleted \"0\" (\"/Users/rtillis/Library/Application Support/rancher-desktop/lima/0\")"
"/private/etc/sudoers.d/rancher-desktop-lima" is up-to-date (or sudo doesn't require a password)
time="2022-01-20T08:34:21-05:00" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2022-01-20T08:34:21-05:00" level=info msg="Starting switch daemon for \"bridged_en10\" network"
time="2022-01-20T08:34:21-05:00" level=fatal msg="failed to run [sudo --user root --group wheel --non-interactive /bin/mkdir -m 775 -p /private/var/run/rancher-desktop-lima]: stdout=\"\", stderr=\"sudo: a password is required\\n\": exit status 1"
2022-01-20T13:34:21.357Z: + limactl start --tty=false /Users/rtillis/Library/Application Support/rancher-desktop/lima/_config/0.yaml
2022-01-20T13:34:21.358Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-01-20T13:34:21.358Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

backgroud.log
2022-01-19T21:58:29.994Z: UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)
2022-01-20T13:31:45.702Z: UnhandledRejectionWarning: TypeError: Promise resolve or reject function is not callable
    at Promise.then (<anonymous>)
2022-01-20T13:31:49.726Z: Stopped Kubernetes backend cleanly.
2022-01-20T13:31:49.726Z: Deleting VM to reset...
2022-01-20T13:31:50.571Z: Deleted VM to reset exited cleanly.
2022-01-20T13:32:11.679Z: Kubernetes was unable to start: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2022-01-20T13:34:15.207Z: Stopped Kubernetes backend cleanly.
2022-01-20T13:34:15.207Z: Deleting VM to reset...
2022-01-20T13:34:16.070Z: Deleted VM to reset exited cleanly.
2022-01-20T13:34:21.365Z: Kubernetes was unable to start: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8218)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by rickytillis** [comment]
1.0.0-beta1 fixed my issue.
