### ISSUE TITLE
KubeClient not picking up correct kubeconfig

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#1536]
## Environment
Windows 10 Pro, 20H2 x64.
Rancher Desktop 1.0.1 (release).
VPN is not applicable.
Container engine: containerd (though this does not matter).

## Steps to reproduce
1. Run `lusrmgr.msc` and change the user's home folder: 
![image](https://user-images.githubusercontent.com/3977982/152883334-f670c46c-0625-4f1b-962b-3766036bbd76.png)
Note that this produces a situation where `%HOMEDRIVE%%HOMEPATH%` (`C:\Users\Jöé Smîth\HomePath`) does not match `%USERPROFILE%` (`C:\Users\Jöé Smîth`).
2. Ensure that `%HOMEDRIVE%%HOMEPATH%\.kube\config` does not exist.
3. Ensure that `%USERPROFILE%\.kube\config` exists and is valid.

## Expected behaviour
The cluster starts successfully, with `%USERPROFILE%\.kube\config` containing modifications to point to the Rancher Desktop cluster.

## Actual behaviour
The cluster fails to start up, because the internal Kubernetes client could not find the cluster:
![image](https://user-images.githubusercontent.com/3977982/152884202-6deded6c-2d3b-4cf8-ae0c-4c925ed756b8.png)

The last few lines of `wsl.log` are:
```
2022-02-07T22:38:20.896Z: Running command wsl --distribution rancher-desktop --exec cat /proc/net/route...
2022-02-07T22:38:21.185Z: Running command wsl --distribution rancher-desktop --exec cat /proc/net/fib_trie...
2022-02-07T22:38:23.028Z: Running command wsl --distribution rancher-desktop --exec wslpath -a -u C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\wsl-helper...
2022-02-07T22:38:23.257Z: Running command wsl --distribution rancher-desktop --exec /mnt/c/Users/Jöé Smîth/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/wsl-helper k3s kubeconfig...
```
(This is a red herring; we actually finished running that command.)

The actual error from `background.log`:
```
2022-02-07T22:38:28.071Z: Kubernetes was unable to start: Error: No active cluster!
    at KubeConfig.makeApiClient (C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\@kubernetes\client-node\dist\config.js:257:19)
    at new Re (C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:13:20132)
    at C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:13:11595
    at tt.action (C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:18973)
    at C:\Users\Jöé Smîth\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:13:11539
```

Relevant lines from `k8s.log`:
```
2022-02-07T22:38:23.026Z: The K3s server is ready on 172.28.88.24:6443.
2022-02-07T22:38:26.196Z: Updating kubeconfig C:\Users\Jöé Smîth\.kube\config...
2022-02-07T22:38:26.252Z: Setting default context...
Switched to context "rancher-desktop".
```

## Additional Information
I believe this is because of an issue in `@kubernetes/client-node`; we may need to bump that.

This may be the underlying issue for #1470 — I'm creating a new issue to avoid taking that over in case the actual cause is different.

**Comment by ericpromislow** [comment]
Can you use something like minikube to start a k8s process with that setup? And after it's running, can `kubectl.exe` find the cluster? Because I modeled the `findHomeDir.ts:findHomeDir()` after the k8s go-client. Given that, I'm not 100% sure `kubectl` uses that `go-client` code.

**Comment by mook-as** [comment]
… I bumped `@kubernetes/client-node` to pick up [your PR](https://github.com/kubernetes-client/javascript/pull/748) to match our code? :) So it should match what we have now.

**Comment by patware** [comment]
Related to https://github.com/rancher-sandbox/rancher-desktop/issues/1470

Is possible that the problem is with "Roaming Profiles" and/or Folder redirections ?

Also, I don't know if it's relevant, but both background.log and wsl.log aren't in plain text. But if force to open it as text, in Visual Studio Code:

background.log
2022-02-07T15:49:11.938Z: event settings-write in main: [object Object], [object Object]
2022-02-07T15:54:48.023Z: event settings-read in main: [object Object]
2022-02-07T15:54:49.741Z: event settings-read in main: [object Object]
2022-02-07T15:57:01.402Z: 2: Child exited cleanly.

wsl.log
2022-02-07T15:56:59.101Z: Running command wsl --list --quiet --running...
2022-02-07T15:56:59.101Z: Capturing output: wsl.exe --list --quiet --running
2022-02-07T15:56:59.203Z: Registered distributions: rancher-desktop
2022-02-07T15:56:59.203Z: Running command wsl --distribution rancher-desktop --exec /usr/local/bin/wsl-service k3s stop...
2022-02-07T15:56:59.203Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service k3s stop
2022-02-07T15:57:00.436Z: Running command wsl --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifstarted docker stop...
2022-02-07T15:57:00.436Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifstarted docker stop
2022-02-07T15:57:00.731Z: Running command wsl --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifstarted buildkitd stop...
2022-02-07T15:57:00.731Z: Running: wsl.exe --distribution rancher-desktop --exec /usr/local/bin/wsl-service --ifstarted buildkitd stop
2022-02-07T15:57:01.103Z: Running command wsl --list --quiet --running...
2022-02-07T15:57:01.103Z: Capturing output: wsl.exe --list --quiet --running
2022-02-07T15:57:01.133Z: /sbin/init exited gracefully.
2022-02-07T15:57:01.278Z: Registered distributions: rancher-desktop
2022-02-07T15:57:01.279Z: Running command wsl --terminate rancher-desktop...
2022-02-07T15:57:01.279Z: Running: wsl.exe --terminate rancher-desktop

k8s.log: empty

**Comment by patware** [comment]
Ha!  I think you're right with the HOMEDRIVE and HOMEPATH.

HOMEDRIVE: U:
HOMEPATH: \
USERPROFILE: C:\Users\calvep
