### ISSUE TITLE
RD failed to start with version 1.1.0 or 1.1.1

### ISSUE THREAD

**Issue by ChBerrich** [rancher-sandbox/rancher-desktop#1740]
### Actual Behavior

RD failed to start after upgrade from 1.0.0/1.0.1 or clean install with version 1.1.0 or 1.1.1.

### Steps to Reproduce

Scenario 1: From version 1.0.0 or 1.0.1 working on my PC with auto update activated, after new version download and RD restart, RD fail to start.

Scenario 2: After uninstall and clean all rancher-desktop directories, clean install with 1.1.0 or 1.1.1 produce same problem, RD fail to start with below error log

### Result

background.log

2022-03-06T22:05:01.902Z: Error starting up: <ref *1> Error: spawnSync C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:161624
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:162210 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049151 more bytes>,
    <Buffer >
  ],
  pid: 22072,
  stdout: <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049151 more bytes>,
  stderr: <Buffer >
}

### Expected Behavior

Have RD running

### Rancher Desktop Version

1.1.1

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 10 Enterprise 21H2

### What CPU architecture are you using?

x64

### Windows User Only

VPN PulseSecure but not connected during the test/problem
No other specific rules, but my PC is managed by my company

Not that Rancher Desktop version 1.0.0 or 1.0.1 is working on my PC after uninstall 1.1.1

**Comment by ericpromislow** [comment]
I've never seen this particular error before, but googling shows `ENOBUFS` indicates memory problems, usually an HTTP server running out of buffer space. That MB for a cert looks suspicious. I'll bring this up with our cert team.

**Comment by mook-as** [comment]
Hmm, if I'm reading the `win-ca` source correctly, it's executing `roots.exe` (via [`execFile`](https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processexecfilefile-args-options-callback) and capturing the output in memory in one go; I wonder if it's somehow failing here because it failed to allocate enough memory (why‽) to hold the output?

Looking at the [source](https://github.com/ukoloff/win-ca/blob/master/n-api/roots.c), it just spits out all of the roots (here, in the `ca` and `root` stores).

**Comment by jandubois** [comment]
> I wonder if it's somehow failing here because it failed to allocate enough memory (why‽) to hold the output?

I'm pretty sure that is the root cause. People have reported that the issue was fixed for them by deleting expired certs, but I think this had nothing to do with the certs themselves, but was just due to reducing the total size needed for all certs.

**Comment by jandubois** [comment]
So I think this is a duplicate of #1072

**Comment by jandubois** [comment]
> Not that Rancher Desktop version 1.0.0 or 1.0.1 is working on my PC after uninstall 1.1.1

This part is confusing me: why is this different in 1.1.1? What are the code changes in this area?

**Comment by boks21** [comment]
Already exists a solution for this issue? I have the same problem after upgrade do 1.1.1

`2022-03-08T12:05:42.212Z: Error starting up: <ref *1> Error: spawnSync C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:161624
    at C:\Users\myuser\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:162210 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\myuser\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 36 35 35 33 30 38 32 30 34 33 64 61 30 30 33 30 32 30 31 30 32 30 32 30 34 37 36 32 39 30 37 65 33 33 30 30 64 30 36 30 39 32 61 38 36 ... 1048922 more bytes>,
    <Buffer >
  ],
  pid: 16836,
  stdout: <Buffer 33 30 38 32 30 36 35 35 33 30 38 32 30 34 33 64 61 30 30 33 30 32 30 31 30 32 30 32 30 34 37 36 32 39 30 37 65 33 33 30 30 64 30 36 30 39 32 61 38 36 ... 1048922 more bytes>,
  stderr: <Buffer >
}`

**Comment by jandubois** [comment]
So I'm tentatively closing this as a duplicate of #1072 for now.

**Comment by ChBerrich** [comment]
Can we reopen this issue, I still get same problem on my corporate PC with version 1.2.1

**server.log**
`2022-03-29T20:19:35.994Z: CLI server is now ready.`

**k8s.log**
`2022-03-29T20:19:35.971Z: Error reading cached version data, discarding: [Error: ENOENT: no such file or directory, open 'C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\rancher-desktop\cache\k3s-versions.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\rancher-desktop\\cache\\k3s-versions.json'
}
2022-03-29T20:19:35.984Z: Error reading cached version data, discarding: [Error: ENOENT: no such file or directory, open 'C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\rancher-desktop\cache\k3s-versions.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\rancher-desktop\\cache\\k3s-versions.json'
}
2022-03-29T20:19:35.984Z: Updating release version cache with 0 items in cache`

**background.log**
`2022-03-29T20:19:36.157Z: Error starting up: <ref *1> Error: spawnSync C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar.unpacked\node_modules\win-ca\lib\roots.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:821:24)
    at Object.execFileSync (node:child_process:867:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:2027)
    at Object.run (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\fallback.js:43:26)
    at api (C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\node_modules\win-ca\lib\index.js:60:10)
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:170134
    at C:\Users\myname.MYCOMPANY-EMEA\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:29:170854 {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  path: 'C:\\Users\\myname.MYCOMPANY-EMEA\\AppData\\Local\\Programs\\Rancher Desktop\\resources\\app.asar.unpacked\\node_modules\\win-ca\\lib\\roots.exe',
  spawnargs: [ 'root', 'ca' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049150 more bytes>,
    <Buffer >
  ],
  pid: 7400,
  stdout: <Buffer 33 30 38 32 30 36 31 61 33 30 38 32 30 34 30 32 61 30 30 33 30 32 30 31 30 32 30 32 31 32 31 31 32 30 32 30 63 38 34 66 37 35 33 36 62 62 61 65 38 39 ... 1049150 more bytes>,
  stderr: <Buffer >
}`

**Comment by mook-as** [comment]
Hi! #1072 wasn't fixed in 1.2.1, so it's expected that you're still seeing the issues — we currently track issues when the fixes are landed for the _upcoming_ release, not when it's been shipped.

**Comment by ChBerrich** [comment]
Ok, thanks for the quick update !
Sorry I open a new issue #1927 as I was not sure that my comment on closed issue will be view
So I wait your next update
