### ISSUE TITLE
Rancher Desktop fail to start, fresh install

### ISSUE THREAD

**Issue by marcelomendes** [rancher-sandbox/rancher-desktop#2139]
### Actual Behavior

Trying to using Rancher Desktop on Debian but since version around 1.2 it stop working (cant precise which version specifically).

### Steps to Reproduce

Just try a fresh install of rancher desktop, either AppImage or .deb package from suse build repo. It doesn't matter if you pick docker or containerd, same error.

### Result

Kubernetes Error
Rancher Desktop 1.3.0 - linux (x64)
Error Starting Kubernetes
Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255

Last command run:
/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl copy /tmp/rd-k3s-install-Vgzwy4/install-k3s 0:bin/install-k3s

Context:
Installing k3s

Some recent logfile lines:
 * /var/log/docker.log: correcting owner
 * Starting Docker Daemon ... [ ok ]
/usr/bin/scp: Connection closed
2022-04-29T13:03:31.062Z: + limactl copy /tmp/rd-k3s-install-Vgzwy4/install-k3s 0:bin/install-k3s
2022-04-29T13:03:31.062Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
2022-04-29T13:03:31.063Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

### Expected Behavior

Rancher desktop ready to be used

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.22.7

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Other Linux

### Operating System / Build Version

Debian GNU/Linux bookworm

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by dgiebert** [comment]
I have a similar issue on Arch while trying to bump the AUR package

```
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 11
/usr/bin/scp: Connection closed
2022-05-02T07:53:56.091Z: + limactl --debug copy /tmp/rd-k3s-install-NMxTzE/install-k3s 0:bin/install-k3s
2022-05-02T07:53:56.091Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
2022-05-02T07:53:56.092Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 255
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141690)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Checking the lima.log in debug mode it tells me:
```
Executing: program /usr/bin/ssh host 127.0.0.1, user dgiebert, command sftp
OpenSSH_9.0p1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /dev/null
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 11
/usr/bin/scp: Connection closed
```
The executed scp command is right above the error and on manual execution fails as well

Seems like sftp is missing in the VM, so I installed `openssh-sftp-server` and restarted the VM, which makes the scp command succeed.

**Comment by marcelomendes** [comment]
@dgiebert could you please elaborate on how you did this manually?

**Comment by dgiebert** [comment]
@marcelomendes Created the following file here: `~/.local/share/rancher-desktop/lima/_config/override.yaml`

```yaml
provision:
- mode: system
  script: |
    #!/bin/sh
    apk add --no-cache openssh-sftp-server
```

If that also fixes it for you, guess they should include that package.

**Comment by marcelomendes** [comment]
> @marcelomendes Created the following file here: `~/.local/share/rancher-desktop/lima/_config/override.yaml`
> 
> ```yaml
> provision:
> - mode: system
>   script: |
>     #!/bin/sh
>     apk add --no-cache openssh-sftp-server
> ```
> 
> If that also fixes it for you, guess they should include that package.

Yes, this made it work! I agree this package should be added, so we don't have to override every factory reset. Thank you for the workaround.
