### ISSUE TITLE
mac-ca throws when one certificate could not be parsed

### ISSUE THREAD

**Issue by marlonchalegre** [rancher-sandbox/rancher-desktop#2163]
### Actual Behavior

Hi guys, I've upgrade from 1.2.1 to 1.3.0 on MacOS and the Rancher Desktop does not open anymore.

### Steps to Reproduce

Upgrade from 1.2.1 to 1.3.0 on MacOs Monterey 12.3.1.

### Result

2022-05-02T20:55:43.128Z: Error starting up: Error: error:0b00008b:X.509 certificate routines:OPENSSL_internal:INVALID_FIELD_FOR_VERSION
    at new X509Certificate (node:internal/crypto/x509:115:21)
    at Rr (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:59085)
    at async Ar (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:58013)
    at async Dr (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:59616)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:85080
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:84931 {
  opensslErrorStack: [
    'error:0c00009e:ASN.1 encoding routines:OPENSSL_internal:NESTED_ASN1_ERROR',
    'error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG',
    'error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines',
    'error:0c000065:ASN.1 encoding routines:OPENSSL_internal:AUX_ERROR'
  ],
  library: 'X.509 certificate routines',
  function: 'OPENSSL_internal',
  reason: 'INVALID_FIELD_FOR_VERSION',
  code: 'ERR_OSSL_X509_INVALID_FIELD_FOR_VERSION'
}

### Expected Behavior

The app should open

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

0

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

12.3.1

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
Hi!
Sorry about that; I believe there is an issue parsing one of the certificates on your system. Would it be possible to check if one of the certificates in your (macOS) Keychain is invalid? I _believe_ there should be an error in Keychain Access, but I'm not 100% sure about that…

(Internal note: we should put all of the loop body around https://github.com/rancher-sandbox/rancher-desktop/blob/278198b8984ce018ebdafa7ba5d28039020ed634/src/main/networking/mac-ca.ts#L67-L81 in a `try`/`catch`, not just the verification.)

**Comment by marlonchalegre** [comment]
I took a look in my Keychain, all certificates are valid  :(

**Comment by mook-as** [comment]
Hmm, that makes it more… _fun_.  Could you try running this shell script (I _think_ `/bin/bash` is still being distributed?) and see if you get any output?  Judging from the error code, there's a certificate that _isn't_ x509v3 but is using x509v3 extensions… maybe.  This may be related to https://crbug.com/boringssl/375.

Of course, it's probably a good idea to review the script before you run it, in case I do something totally dumb and delete unintended files…

[list-certs.sh.gz](https://github.com/rancher-sandbox/rancher-desktop/files/8612328/list-certs.sh.gz)

**Comment by marlonchalegre** [comment]
Yeah, You are right! There is a certificate using extensions but is no a x509v3

Certificate contains X509v3 extensions, but is not X509v3

The fun part, this looks like a certificate from a security plugin that some Brazilians bank use. The real fun part, I did not installed it.

:D

**Comment by mook-as** [comment]
> Should keep this issue opened to work in some way to better handling this kind of issue (bug?) from RD or could we close it?

Please keep this open; I still need to write a PR to handle this better (by skipping the _one_ certificate, rather than falling over).
