### ISSUE TITLE
Dashboard's Download KubeConfig and Copy KubeConfig to Clipboard feature not working (no action)

### ISSUE THREAD

**Issue by kable-wilmoth** [rancher-sandbox/rancher-desktop#2208]
### Actual Behavior

Using the Dashboard I want to download the KubeConfig file or copy it to my clipboard so that I can feed it to other tools.

The two buttons are enabled, the UI implies I am clicking them but nothing happen.  There is no UI change (like a download dialog or action), nothing is in my downloads folder, nothing is in my clipboard.

### Steps to Reproduce

Downloaded and installed Mac Apple silicon: dashboard version: desktop-v2.6.3.beta.12. RancherDesktop version 1.3.0

Had previous docker desktop installations (even pre 1.0).
Received an error about rights to clean up /usr/local/bin
I deleted nerdctl and kubectl which used to point to older rancher.
I clicked the Factory Reset button.
The UI closed down.  I re-opened and didn't receive any warnings.
The cluster is up and running, looks healthy, can use kubectl to interact with it.

Can not download/copy to clipboard the KubeConfig

### Result

Nothing happens when I click either button

### Expected Behavior

I get a downloaded KubeConfig or its contents copied to my clipboard

### Additional Information

Had previous installs at some point but it seems cleaned up.
Had a script in my zshrc that generated KUBECONFIG but I removed it (now kubectl works correctly, different issue)

### Rancher Desktop Version

1.3.0

### Rancher Desktop K8s Version

1.23.6

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Monterey 12.3.1 (21E258)

### What CPU architecture are you using?

arm64 (Apple Silicon)

**Comment by krptg0** [comment]
I can reproduce this issue, on Windows 11 with same version numbers.

**Comment by rak-phillip** [comment]
Thanks for raising the issue, we can reproduce on our end as well. Clicking `Download KubeConfig` definitely produces an error:

```
TypeError: Cannot read properties of undefined (reading 'includes')
    at actions.js:23:17
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at y.request (actions.js:19:56)
```

**Comment by rak-phillip** [comment]
Related #2487

**Comment by bananflugan** [comment]
Any news regarding this? Still the same issue with latest version which currently is 1.6.1.

**Comment by bparinas** [comment]
same error in RD version 1.6.2 (win11)

Download KubeConfig or Copy KubeConfig to Clipboard no output

**Comment by MarcStdt** [comment]
+1

**Comment by Roguito** [comment]
RD 1.7 on Win11, encountering same problem. Is this issue STILL open?

**Comment by rak-phillip** [comment]
@Roguito thanks for confirming that this is still an issue for RD 1.7. 

To confirm, yes, this issue is still open. We are working on a feature to more tightly integrate Rancher Dashboard and Desktop. I hope to see more action on this issue in the near future.

**Comment by seyhbold** [comment]
Until this is fixed we can workaround using the `rdctl` command:

```
rdctl shell sudo k3s kubectl config view --raw > rancher-desktop.ym
```

Places the config into `rancher-desktop.yml`

**Comment by joshuamkite** [comment]
So at this point this issue has been outstanding for more than 2 years and could be a showstopper for newbies. If it isn't going to be fixed in any reasonable time and since @seyhbold solution does not readily appear in the official docs, could we look at hiding the (currently misleading) UI elelements and updating the docs?

**Comment by demonkoryu** [comment]
Same here, Linux Mint Cinnamon

**Comment by kiranmenon** [comment]
same here on Mac silicon rd  1.15.0.
No action on happening on clicking download kubeconfig button

**Comment by StefanD986** [comment]
Workaround for me from Rancher web interface is: Go to ☰ Menu -> Cluster Management -> Click three dots ⁝ -> Download KubeConfig

**Comment by jandubois** [comment]
There is unfortunately nothing we can do until we update the Cluster Dashboard to a more recent version. Currently we are using a very old fork of the dashboard from Rancher Manager, that is impossible to update with the latest upstream changes.

However, there is work in progress to integrate the upstream version directly without needing a fork. I hope this will land in Rancher Desktop 1.18 early next year. It is not ready for the 1.17 release.

**Comment by jandubois** [comment]
@rak-phillip This is still not working in #8147

**Comment by jandubois** [comment]
> this issue [...] could be a showstopper for newbies.

So while I understand that having buttons that don't work is confusing, and hope we can fix this. But I'm wondering what the actual use case is:

Rancher Desktop already updates the local `~/.kube/config` file with the `rancher-desktop` context pointing to the local cluster. Why would a "newbie" need a separate copy of the config in a file or the clipboard?

Unlike the full Rancher Manager, the builtin Cluster Dashboard only works for the local cluster provided by Rancher Desktop. So the copy/download buttons will never provide any different config. And I'm not sure if the config provided would point to `127.0.0.1` and not to the internal IP address of the VM, so would need to be modified before it could be used from the host.

**Comment by jandubois** [comment]
> I'm wondering what the actual use case is:

It looks like getting this feature to work is non-trivial because it relies on some API/infrastructure from Rancher Manager that is not present in Rancher Desktop.

Given that the kubeconfig is already installed into `~/.kube/config`, I would suggest that we just remove (or hide) the buttons, to avoid confusing the user.

**Comment by Ramsey77** [comment]
You can pull the rancher config from the default location which, on a mac, is /Users/(YourUserName)/.kube/config
This file contains your cluster information and context so if you are working on several clusters or contexts you can switch between them using export like so:
export KUBECONFIG=/Users/(YouUserName)/.kube/config and then view which context you are in with:
kubectl config get-contexts.
