### ISSUE TITLE
 Test Plan 1.4: OpenSUSE: Test #13 - failed to restart kubernetes (Cert error?)

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#2276]
### Actual Behavior

Ran `Reset Kubernetes` and got a failure dialog with this info:
```
Error Starting Kubernetes
Error: /home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/resources/linux/lima/bin/limactl exited with code 1
Last command run:
/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/resources/linux/lima/bin/limactl start --tty=false 0

Context:
Starting virtual machine
```

Pertinent log files:
background.log (note older logs):
```
2022-05-26T19:43:52.810Z: Rejecting invalid certificate: encountered errors: Error: Invalid PEM formatted message.
    at Object.pem.decode (/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/node_modules/node-forge/lib/pem.js:192:11)
    at /home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/dist/app/background.js:29:50666
    at dn (/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/dist/app/background.js:29:50766)
    at Array.filter (<anonymous>)
    at Vn (/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/dist/app/background.js:29:56437)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async g.<anonymous> (/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/dist/app/background.js:29:99153)
2022-05-26T19:43:52.810Z: Skipping certificate, cannot decode
2022-05-26T19:43:52.813Z: Rejected cert expired on Wed, 15 Dec 2021 08:00:00 GMT issued by Cybertrust Global Root
2022-05-26T19:43:52.816Z: Rejected cert expired on Sat, 21 May 2022 04:00:00 GMT issued by GeoTrust Global CA
2022-05-26T19:43:52.817Z: Rejected cert expired on Wed, 15 Dec 2021 08:00:00 GMT issued by GlobalSign
2022-05-26T19:43:52.820Z: Rejected cert expired on Wed, 17 Mar 2021 18:33:33 GMT issued by QuoVadis Root Certification Authority
2022-05-26T19:43:52.821Z: Rejected cert expired on Tue, 06 Apr 2021 07:29:40 GMT issued by Sonera Class2 CA
2022-05-26T20:10:47.865Z: Kubernetes was unable to start: Error: /home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/app.asar/dist/app/background.js:17:141825)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  command: [
    '/home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '0'
  ]
}

```

k3s.log:
```
W0526 20:10:35.628118    8803 reflector.go:441] github.com/flannel-io/flannel/subnet/kube/kube.go:379: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
time="2022-05-26T20:10:35Z" level=error msg="Tunnel endpoint watch channel closed: {ERROR &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:Failure,Message:an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding,Reason:InternalError,Details:&StatusDetails{Name:,Group:,Kind:,Causes:[]StatusCause{StatusCause{Type:UnexpectedServerResponse,Message:unable to decode an event from the watch stream: context canceled,Field:,},StatusCause{Type:ClientWatchDecoding,Message:unable to decode an event from the watch stream: context canceled,Field:,},},RetryAfterSeconds:0,UID:,},Code:500,}}"

```
lima.log (not very helpful):
```
2022-05-26T20:10:47.863Z: + limactl start --tty=false 0
2022-05-26T20:10:47.864Z: Error: /home/ericp/lab/rd/rancher-desktop-v1.4.0-as-1.3.0-298-c1ed19db/resources/resources/linux/lima/bin/limactl exited with code 1
```

### Steps to Reproduce

see above

### Result

see above

### Expected Behavior

see above

### Additional Information

see above

### Rancher Desktop Version

1.3.0-298-c1ed19db

### Rancher Desktop K8s Version

1.22.9

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

OpenSUSE Leap 15

### What CPU architecture are you using?

x64

**Comment by mook-as** [comment]
I believe the cert issues are a red herring, and are unrelated to the issue.

**Comment by gaktive** [comment]
@prabalsharma as part of the next test run, can someone check to see if this test is still failing?

**Comment by prabalsharma** [comment]
This issue was not observed in last test run on build 1.5.0-471-gda475b63

**Comment by jandubois** [comment]
@prabalsharma So should this issue be closed, and we can open a new one if the failure re-appears?
