### ISSUE TITLE
RD 1.4.1. Unable to use on OpenSUSE Leap 15.3 (No kube contexts)

### ISSUE THREAD

**Issue by andreas-kupries** [rancher-sandbox/rancher-desktop#2639]
### Actual Behavior

Installed RD using the RPM instructions for openSUSE

> sudo zypper addrepo https://download.opensuse.org/repositories/isv:/Rancher:/stable/rpm/isv:Rancher:stable.repo
sudo zypper install rancher-desktop

I got `rancher-desktop 1.4.1-lp153.2.6`.

  - Started, got dialog `TypeError: Cannot read properties of undefined (reading 'clusters')`
  - After clicking ok system continued, initialization dialog opened.
  - Kept to defaults (containerd, kube 1.24.3, automatic PATH, kube on)
  - Main window appears. System pulls kube images, starts VM, starts k3s, seems to be running in the end.
  - Then a larger dialog for the above type error appears, with a bit more logs (see (**) below)
  - Clicking away ...
  - The `Kubernetes Contexts` menu entry (system tray icon) does not show anything.
  - Trying to get info from the command line, using the RD binaries does not work either
    > work@tagetarl:~/SUSE/dev/epinio> ~/.rd/bin/kubectl config get-contexts
I0727 13:14:04.401066   19684 versioner.go:58] invalid configuration: no configuration has been provided
CURRENT   NAME   CLUSTER   AUTHINFO   NAMESPACE

  - Switching to `dockerd/moby` as container engine does not change anything. Except that the redirection docker socket allows me to see with `docker ps` that there are indeed a number k3d-related containers running somewhere (VM?).

RD seems to be partially running, and partially broken, and the cluster not accessible for use with kubectl, helm, etc.

(**)
```
2022-07-27T08:38:40.141Z: Configuration /etc/rancher/k3s/k3s.yaml not present in lima vm; will check again...
2022-07-27T08:38:41.201Z: Configuration /etc/rancher/k3s/k3s.yaml not present in lima vm; will check again...
2022-07-27T08:38:42.269Z: Configuration /etc/rancher/k3s/k3s.yaml not present in lima vm; will check again...
2022-07-27T08:38:43.361Z: Error starting lima: TypeError: Cannot read properties of undefined (reading 'clusters')
    at KubeConfig.loadFromString (/opt/rancher-desktop/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:103:56)
    at KubeConfig.loadFromFile (/opt/rancher-desktop/resources/app.asar/node_modules/@kubernetes/client-node/dist/config.js:77:14)
    at Function.findKubeConfigToUpdate (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:157078)
    at Mt.updateKubeconfig (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:157977)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to Reproduce

See above

### Result

See above

### Expected Behavior

A cluster I can talk to with kubectl, helm, etc.

### Additional Information

No Docker Desktop on the machine. Did have SUSE's `docker` package installed. Affected the switch to the `dockerd/moby` engine a bit, in that RD asked for and was allowed to redirect the `/var/run/docker.sock` to `$HOME/.rd/docker.sock`.

Remember however that the reported issues happened regardless of chosen container engine.

Attached, all the logs: [rd-logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/9198496/rd-logs.zip)

:warning: Note that I tried both container engines, with the same results, as described.
The selector below does not allow a choice of `both` however. And is required.
Decided to select `containerd` as it was the initial engine, being default.

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

default (1.24.3)

### Which container runtime are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

OpenSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by andreas-kupries** [comment]
As some additional info, using the commands

```
LIMA_HOME=$HOME/.local/share/rancher-desktop/lima /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl shell 0 -- sudo cat /etc/rancher/k3s/k3s.yaml | sed 's/default/rancher-desktop/g' > rd-config
 cat rd-config 
 KUBECONFIG=$PWD/rd-config kubectl cluster-info
 KUBECONFIG=$PWD/rd-config kubectl get nodes
 KUBECONFIG=$PWD/rd-config kubectl get pods
```

given to me by @nunix I get access to the cluster.
