### ISSUE TITLE
RD can't connect to Docker Daemon in VM with Ubuntu 22

### ISSUE THREAD

**Issue by bruno-lopes** [rancher-sandbox/rancher-desktop#2654]
### Actual Behavior

I have created a new VM with Ubuntu 22, and followed this (guide)[https://docs.rancherdesktop.io/getting-started/installation/#linux]  in order to install Rancher Desktop.

When I open Rancher Desktop, it fails to start with the following error:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 * ERROR: k3s failed to start
2022-07-29T12:20:30.894Z: + limactl shell --workdir=. 0 sudo /sbin/rc-service --ifnotstarted k3s start
2022-07-29T12:20:30.894Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
2022-07-29T12:20:30.894Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141990)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  command: [
    '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    '/sbin/rc-service',
    '--ifnotstarted',
    'k3s',
    'start'
  ]
}
```

### Steps to Reproduce

1. Create a virtual machine in Virtual Box
2. Install Ubuntu 22.04
3. Follow this guide (https://docs.rancherdesktop.io/getting-started/installation/#linux) to install Rancher Desktop
4. Configure RD to use dockerd (moby) as Container Runtime

### Result

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 * ERROR: k3s failed to start
2022-07-29T12:20:30.894Z: + limactl shell --workdir=. 0 sudo /sbin/rc-service --ifnotstarted k3s start
2022-07-29T12:20:30.894Z: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
2022-07-29T12:20:30.894Z: Error starting lima: Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:17:141990)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  command: [
    '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'shell',
    '--workdir=.',
    '0',
    'sudo',
    '/sbin/rc-service',
    '--ifnotstarted',
    'k3s',
    'start'
  ]
}
```

### Expected Behavior

Rancher Desktop should start without problems.

### Additional Information

![Error1](https://user-images.githubusercontent.com/2408316/181760185-f4f6c583-e138-477a-9ad7-577aef561ac1.png)
[background.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220002/background.log)
[cri-dockerd.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220003/cri-dockerd.log)
[ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220004/ha.stderr.log)
[ha.stdout.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220005/ha.stdout.log)
[lima.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220006/lima.log)
[serial.log](https://github.com/rancher-sandbox/rancher-desktop/files/9220007/serial.log)

### Rancher Desktop Version

1.4.1

### Rancher Desktop K8s Version

1.22.12

### Which container runtime are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by rak-phillip** [comment]
I was able to reproduce this error by performing the following:

1. Install Rancher Desktop v1.5.0 in an Ubuntu VM
2. Select Docker for the container Runtime
3. Deny sudo access when prompted

Doing so will put Rancher Desktop into the following state:

![image](https://user-images.githubusercontent.com/835961/181848529-3fd11917-56ee-4cc6-9706-d7589851753a.png)

**Comment by rak-phillip** [comment]
@bruno-lopes thanks for raising this issue an helping to make Rancher Desktop better!

It looks like Rancher Desktop can't create the socket in the default location because it wasn't given administrative access. I think there are two ways you can try to work around this issue while we work on a fix

1. Enable Administrative Access in Preferences & Restart Rancher Desktop (you may need to reboot your VM as well)
2. If you can't enable Administrative Access, then you could try running `docker context use rancher-desktop` in your terminal to see if that might help

Can you either of those a try and let us know that resolves the issue for you?

**Comment by rak-phillip** [comment]
Note: we should be able to easily detect when Administrative Access can't be reached and the Docker socket can't be reached. There's an opportunity here to provide a clear error message with tips for potential fixes

**Comment by bruno-lopes** [comment]
@rak-phillip Thanks for your quick response!

Currently, I use RD in Linux Mint without problem in those two modes that you listed.

In Ubuntu 22, I'm not able to run it in none of them. Disabling Adminstrative Access is not creating the context rancher-desktop, and the error is the same. In Mint, it does create this context.

I have recreated the VM and reinstalled Ubuntu and RD, but I am still getting this error. I tried with the AppImage of RD, but the error persists. Is there any special configuration that must be done in VirtualBox? Thanks!

PS: I'm trying to install in the VM because a friend of mine tried to install RD in Ubuntu 22 without success to. I was trying to reproduce the error, but I got this error instead.

**Comment by rak-phillip** [comment]
Thanks for the follow up! There's not any special configuration that I'm aware of outside of enabling nested virtualization and making sure that your VM meets the [recommended requirements](https://docs.rancherdesktop.io/getting-started/installation#requirements-2).

I was originally testing in 20.04 so I tried again in different VM for 22.04. Strangely enough, I don't see the `rancher-desktop` context, but a `loaded-context` instead. The Ubuntu version definitely appears to strongly influence this behavior..

**Comment by bruno-lopes** [comment]
@rak-phillip, does RD use the docker template located at '/opt/rancher-desktop/resources/resources/linux/lima/share/lima/examples/docker.yaml'?

I used 'limactl' to start a new machine with the following command:

```
/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start  /opt/rancher-desktop/resources/resources/linux/lima/share/lima/examples/docker.yaml
```

And I have created a docker context using this:

``` 
docker context create lima-docker --docker "host=unix:///home/bruno/.lima/docker/sock/docker.sock"
```
 
Then, I set the docker context: 

```
docker context use lima-docker
```
And followed the logs with this:

```
tail -f /home/bruno/.lima/docker/serial.log
```

It was very very slow to really start docker engine.

When I was trying to see docker containers with:

```
docker ps
```

I got the following error:

```
error during connect: Get "http://%2Fhome%2F/bruno%2F.lima%2Fdocker%2Fsock%2Fdocker.sock/v1.24/containers/json": read unix @->/home/bruno/.lima/docker/sock/docker.sock: read: connection reset by peer"
```
My point is that RD is failing because the Docker Engine is really not read. In cri-dockerd.log file that I have attached here, we can see that RD tries 11 times before failing:

```
time="2022-07-29T12:20:41Z" level=info msg="Connecting to docker on the Endpoint unix:///var/run/docker.sock"
time="2022-07-29T12:20:41Z" level=info msg="Start docker client with request timeout 0s"
time="2022-07-29T12:20:41Z" level=fatal msg="failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

Would it be possible to increase the number of times RD tries to connect with Docker, or the timeout in order to wait docker engine to really start?

Thanks!

**Comment by bruno-lopes** [comment]
After the error detected by RD, I have waited a few minutes, and I could access Docker. I think the real problem is that when RD tries to connect to Docker, it is not ready, so it fails.

In a normal machine, like my notebook, it doesn't occur, and RD works like a charm.
