### ISSUE TITLE
Rancher Desktop does not start

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#3573]
### Actual Behavior

Rancher Desktop does not start when started through the system launcher.

### Steps to Reproduce

1. Install Rancher Desktop version `9.main.1670447570.611b633-805.1` via `zypper`.
2. Run it and wait.

### Result

A Rancher Desktop window never appears, but running `ps` shows Rancher Desktop processes.

### Expected Behavior

Rancher Desktop should start successfully.

### Rancher Desktop Version

9.main.1670447570.611b633-805.1

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Other Linux

### Operating System / Build Version

openSUSE Leap 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

rpm

**Comment by jandubois** [comment]
How long did you wait? I've seen it take 1min or longer for the window to appear.

I don't know what was going on, but it looked like it was downloading 1.6.2 as an "upgrade" to the CI build before showing the window.

**Comment by adamkpickering** [comment]
I waited about 3 minutes I think. It was definitely more than a minute - I set a timer for that amount of time.

**Comment by jandubois** [comment]
That is worrying. Let's see if somebody else reproduces it with RC1 testing

**Comment by ericpromislow** [comment]
On SUSE, when I try running `./rancher-desktop` from https://github.com/rancher-sandbox/rancher-desktop/actions/runs/3644670581 I get this error message in the console:
```
./rancher-desktop 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/ericp/lab/rd/rd-v1.7.0-rc1/resources/app.asar.unpacked/node_modules/ffi-napi/build/Release/ffi_bindings.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/home/ericp/lab/rd/rd-v1.7.0-rc1/resources/app.asar/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/home/ericp/lab/rd/rd-v1.7.0-rc1/resources/app.asar/node_modules/ffi-napi/lib/bindings.js:8:43)
[26832:1208/114209.202819:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[26832:1208/114209.205920:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

with the following processes running, but doing nothing:
```
$ ps auxww
me    26796  4.8  1.1 21799284 179344 pts/10 Sl+ 11:42   0:01 /HOME/rd-v1.7.0-rc1/rancher-desktop --enable-crashpad
me    26799  0.0  0.3 17188336 49628 pts/10 S+   11:42   0:00 /HOME/rd-v1.7.0-rc1/rancher-desktop --type=zygote --no-zygote-sandbox --enable-crashpad --enable-crashpad
me    26800  0.0  0.3 17188328 49728 pts/10 S+   11:42   0:00 /HOME/rd-v1.7.0-rc1/rancher-desktop --type=zygote --enable-crashpad --enable-crashpad
me    26802  0.0  0.0 17188328 10392 pts/10 S+   11:42   0:00 /HOME/rd-v1.7.0-rc1/rancher-desktop --type=zygote --enable-crashpad --enable-crashpad
me    26832  0.3  0.4 17467532 80376 pts/10 Sl+  11:42   0:00 /HOME/rd-v1.7.0-rc1/rancher-desktop --type=gpu-process --enable-crashpad --enable-crash-reporter=36c5efb2-c1cc-4e81-b452-c4f1d3145307,no_channel --user-data-dir=/home/me/.config/Rancher Desktop --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,7817141814334533626,18188463306045530585,131072 --disable-features=SpareRendererForSitePerProcess
me    26879  0.0  0.3 17254020 55044 pts/10 Sl+  11:42   0:00 /HOME/rd-v1.7.0-rc1/rancher-desktop --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --enable-crashpad --enable-crash-reporter=36c5efb2-c1cc-4e81-b452-c4f1d3145307,no_channel --user-data-dir=/home/me/.config/Rancher Desktop --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,7817141814334533626,18188463306045530585,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad
```

**Comment by ericpromislow** [comment]
Could be due to this:
```
~/lab/rd/rd-v1.7.0-rc1> objdump -T resources/app.asar.unpacked/node_modules/ffi-napi/build/Release/ffi_bindings.node | grep GLIBC_2.34
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.34  dlclose
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.34  dlsym
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.34  dlerror
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.34  dlopen
```
