### ISSUE TITLE
How to configure RD to use an internet proxy?

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#384]
From Rancher User Slack:

```
Updating release version cache
FetchError: request to https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

I guess both RD and k3s inside the VM need to be configured for this. We should have UI support for this, as user environment variables for `https_proxy` etc will likely not be visible to RD when started via `launchd`.

**Comment by gregsidelinger** [comment]
This does appear to prevent Rancher Desktop from even launching with the current 0.3.0 release on MacOS without direct internet access.  Also setting the standard proxy env vars and launching from the command line does not appear to do anything.

**Comment by gaktive** [comment]
This scenario is relying on a non-transparent proxy so we'd need to rely on a global proxy setting.
