### ISSUE TITLE
Launch error on Windows 10

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#408]
Installed 0.3.0 on a Windows 10 laptop. Installation went fine, but the app launch fails with below pop up message.

![image](https://user-images.githubusercontent.com/59538726/125366912-fb0d8c00-e32b-11eb-8feb-6f7e8165230b.png)

Here are the logs:

wsl.log

```
Registered distributions: 
Registered distributions: 
WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
```

background.log

```
app version: 0.3.0
{
  version: 2,
  kubernetes: { version: 'v1.19.11', memoryInGB: 2, numberCPUs: 2, port: 6443 },
  portForwarding: { includeKubernetesServices: false },
  images: { showAll: true },
  telemetry: true,
  updater: true
}
Kubernetes was unable to start: Error: wsl.exe exited with code 4294967295
    at ChildProcess.<anonymous> (C:\Users\Gunasekhar Matamalam\AppData\Local\Programs\Rancher Desktop\resources\app.asar\dist\app\background.js:1:7459)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

**Comment by gunamata** [comment]
`wslconfig /u rancher-desktop` fixed the issue on my laptop.
I will keep the ticket open till I get a chance to test the fix again when my RD installation throws this error next time.

**Comment by gunamata** [comment]
Initially, there were issues launching the app on my windows machine. Various fixes, improvements over the past few releases, the app is stable now.
