### ISSUE TITLE
"TypeError: Invalid Version" after Factory Reset on openSUSE 

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop#4177]
### Actual Behavior

Do a factory-reset, don't clear the existing K8s images. On restart, I get this error message:
```
Error Starting Kubernetes
- TypeError: Invalid Version:
Context:
- Installing k3s
Some recent logfile lines:
2023-03-13T23:02:51.420Z: > .../limactl shell --workdir=. 0 sudo bin/install-k3s v1.26.2+k3s1 .../k3s
2023-03-13T23:02:51.421Z: Error starting lima: TypeError: Invalid Version: 
    at new SemVer (/.../node_modules/semver/classes/semver.js:38:13)
    at compare (/.../node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/.../node_modules/semver/functions/gte.js:2:30)
    at X.requiresCRIDockerd...
```

### Steps to Reproduce

See above.

### Result

Error dialog and I need to first try resetting K8s, and then restarting the app.

Error message on restart:
```
Error: .../limactl exited with code 1

Last command run:
/.../limactl shell --workdir=. 0 sudo /sbin/rc-service --ifstarted buildkitd stop

Context:
Stopping services

Some recent [logfile](app://./index.html#) lines:
    '0',
    'sudo',
    '/sbin/rc-service',
    '--ifstarted',
    'k3s',
    'stop'
  ]
}
2023-03-13T23:07:18.855Z: Lima: executing: sudo /sbin/rc-service --ifstarted buildkitd stop: Error: /home/ericp/lab/rd/rd-v1.8.0-rc1/resources/resources/linux/lima/bin/limactl exited with code 1
```

### Expected Behavior

It should just start up with the new settings.

### Rancher Desktop Version

1.8rc1

### Rancher Desktop K8s Version

1.25.7

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

openSUSE 15.3

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment]
And one day later, I can't repro this
