### ISSUE TITLE
Uncaught Exception: No native build was found for platform=darwin arch=arm64 runtime=electron [...] on 1.8.0 mac aarch64

### ISSUE THREAD

**Issue by apolds** [rancher-sandbox/rancher-desktop#4217]
After the update of rancherDesktop to 1.8.0 on macOS 13.2.1 (aarch64), i get the following Error on application startup:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=107 uv=1 armv=8 libc=glibc node=16.15.0 electron=20.3.8
loaded from: /Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/ref-napi

at load.path (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:59:9)
at load (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/node-gyp-build/index.js:21:30)
at Object.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/ref-napi/lib/ref.js:8:53)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
at c._load (node:electron/js2c/asar_bundle:5:13343)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by jandubois** [comment]
Apologies! This was a bug introduced when building the signed release binaries, and we only uploaded the corrected `*.dmg` file. I've now replaced the `*.zip` with the right version as well, so please download again, and everything should work.

Let us know if you have any other issues!

**Comment by arimus** [comment]
Very strange. I get this when building from main for the first time. Fresh checkout. Regression or something else?

```
 WARN  Compiled with 1 warnings                                                                                                                                                             friendly-errors 10:13:13


 WARN  in ./pkg/rancher-desktop/store/prefs.js                                                                                                                                              friendly-errors 10:13:13

Module not found: Error: Can't resolve '~/assets/brand' in '/Users/arimus/workspace/rancher-desktop/pkg/rancher-desktop/store'                                                              friendly-errors 10:13:13
                                                                                                                                                                                            friendly-errors 10:13:13
ℹ Waiting for file changes                                                                                                                                                                                  10:13:13
ℹ Memory usage: 322 MB (RSS: 680 MB)                                                                                                                                                                        10:13:13
ℹ Listening on: http://localhost:8888/                                                                                                                                                                      10:13:13
No issues found.                                                                                                                                                                                            10:13:13
App threw an error during load
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=107 uv=1 armv=8 libc=glibc node=16.15.0 electron=20.3.8
    loaded from: /Users/arimus/workspace/rancher-desktop/node_modules/ref-napi

    at load.resolve.load.path (/Users/arimus/workspace/rancher-desktop/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/Users/arimus/workspace/rancher-desktop/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/Users/arimus/workspace/rancher-desktop/node_modules/ref-napi/lib/ref.js:8:53)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```
