### ISSUE TITLE
Test case 90 (Install Extensions - UI) fails

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/rancher-desktop#4473]
### Actual Behavior

When trying to install the Epinio extension through the UI, it does not install and displays the error message "Unprocessable Entity".

### Steps to Reproduce

1. Start Rancher Desktop. Wait for it to start completely.
2. Go to Extensions > Epinio and click the "Install" button.

### Result

The Epinio extension does not install. See the screenshot.

![image](https://user-images.githubusercontent.com/19395776/232547989-11907ac7-d981-4807-9a89-790866d1826e.png)

### Expected Behavior

The Epinio extension should install.

### Additional Information

extensions.log has the following contents (with debug mode enabled):
```
2023-04-17T18:03:41.551Z: Creating new extension manager...
unpacking ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest (sha256:7df39d89729cc27964dafbe53667932462416bcad5b6cd05524ec732d6eaa283)...
Loaded image: ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest
2023-04-17T18:04:36.727Z: Failed to install extension ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.23.5, cleaning up: E [Error]: Could not copy host binary /linux/jq
    at /opt/rancher-desktop/resources/app.asar/dist/app/0.js:1:3435
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 3)
    ... 3 lines matching cause stack trace ...
    at async Ui.installExtension (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:16:82712) {
  cause: Error: Failed to create container for ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.23.5
      at jn.mountImage (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:4:121024)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async jn.copyFile (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:4:122067)
      at async /opt/rancher-desktop/resources/app.asar/dist/app/0.js:1:3344
      at async Promise.all (index 3)
      at async I.installHostExecutables (/opt/rancher-desktop/resources/app.asar/dist/app/0.js:1:3306)
      at async I.install (/opt/rancher-desktop/resources/app.asar/dist/app/0.js:1:1569)
      at async Oo.installExtension (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:16:143988)
      at async Ui.installExtension (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:16:82712),
  code: 1,
  [Symbol(extension-error)]: 0
}
```

### Rancher Desktop Version

c38556e3

### Rancher Desktop K8s Version

1.26.3

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

deb

**Comment by jandubois** [comment]
Can you please enabled Debug logging (on Troubleshooting page) and try again? Then include the output of the `extensions.log`.

**Comment by adamkpickering** [comment]
I want to write a comment here to record what I've learned while debugging this, so we have some record of it.

- The problem happens both when using containerd and moby. However, it happens much less often with moby: I have to try installing the Epinio extension ~5 times to get an install to fail.

- The problem results from calls to external commands (via `this.vm.execCommand` for `NerdctlClient` and via `this.docker` for `MobyClient`) that return nothing from stdout, when we need to use the information in stdout for some subsequent step.

- @mook-as thought it might have something to do with sshd's `MaxSessions` setting. See https://github.com/rancher-sandbox/rancher-desktop/pull/3971 for more info. I did try increasing `MaxSessions`, but it didn't appear to have an effect.

- When the install fails when using moby, it always (as far as I can tell) fails with the below message. This seems to imply that the problem is *not* `MaxSessions`, because SSH has nothing to do with this command - it is just a call to `docker` on the host via `spawnFile`. Perhaps the problem is with `spawnFile`?

```
2023-04-18T16:27:11.406Z: Failed to install extension ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.23.5, cleaning up: ExtensionErrorImpl: Could not copy host binary /linux/epinio-http
    at /home/adam/dev/rancher-desktop/dist/app/0.js:188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 4)
    ... 3 lines matching cause stack trace ...
    at async HttpCommandServer.installExtension (/home/adam/dev/rancher-desktop/dist/app/background.js:33464:38) {
  cause: Error: Failed to create container ghcr.io/rancher-sandbox/epinio-desktop-extension:0.0.23.5
      at MobyClient.makeContainer (/home/adam/dev/rancher-desktop/dist/app/background.js:23637:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async MobyClient.copyFile (/home/adam/dev/rancher-desktop/dist/app/background.js:23667:27)
      at async /home/adam/dev/rancher-desktop/dist/app/0.js:185:17
      at async Promise.all (index 4)
      at async ExtensionImpl.installHostExecutables (/home/adam/dev/rancher-desktop/dist/app/0.js:183:9)
      at async ExtensionImpl.install (/home/adam/dev/rancher-desktop/dist/app/0.js:114:13)
      at async BackgroundCommandWorker.installExtension (/home/adam/dev/rancher-desktop/dist/app/background.js:1140:21)
      at async HttpCommandServer.installExtension (/home/adam/dev/rancher-desktop/dist/app/background.js:33464:38),
  code: 1,
  [Symbol(extension-error)]: 0
}
```

@mook-as if you have anything to add please do!
