### ISSUE TITLE
Visual Studio Code devcontainer mounting folder error

### ISSUE THREAD

**Issue by Mk-arc** [rancher-sandbox/rancher-desktop#4735]
I am running Rancher Desktop 1.8.1. on Windows and Visual Studio Code.

I am using the docker integration with a .devcontainer setting.

We are evaluating moving from Docker Desktop to Rancher Desktop. Our setup works perfectly fine with Docker Desktop. However the following configuration in our .devcontainer setting causes errors only with rancher desktop:

```
    "mounts": [
        "source=/c/docker_shared,target=/home/shared,type=bind,consistency=cached"
    ],
```
Somehow this mount fails when running with rancher desktop, but works well with docker desktop. Removing this mounts setting and everything else also works with rancher desktop.
```
[6407 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR -p 22131:22131/tcp -p 22132:22132/tcp -p 22460:22460/tcp -p 22131:22131/udp -p 22132:22132/udp -p 22460:22460/udp --mount type=bind,source=c:\Users\<user>\Documents\teodor_evo,target=/workspaces/teodor_evo,consistency=cached --mount source=/c/docker_shared,target=/home/shared,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=c:\Users\<user>\Documents\teodor_evo\nodes\autonomy -l devcontainer.config_file=c:\Users\<user>\Documents\teodor_evo\nodes\autonomy\.devcontainer\devcontainer.json -e BUILD_TARGET=_docker_autonomy --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --entrypoint /bin/sh -l devcontainer.metadata=[{"postCreateCommand":"./${workspaceFolder}/setup.sh","postStartCommand":"nohup bash -c 'roscore &'","customizations":{"vscode":{"settings":{"cmake.buildDirectory":"${workspaceFolder}/build_docker_autonomy","cmake.sourceDirectory":"${workspaceFolder}/src","cmake.configureSettings":{"CMAKE_PREFIX_PATH":"/opt/ros/noetic","BOOST_LIBRARYDIR":"/usr/lib/x86_64-linux-gnu","ENABLE_TESTS":"ON"}},"extensions":["ms-vscode.cpptools","ms-vscode.cmake-tools"]}},"mounts":["source=/c/docker_shared,target=/home/shared,type=bind,consistency=cached"],"containerEnv":{"BUILD_TARGET":"_docker_autonomy"},"remoteUser":"root"}] telebucket:5000/autonomy:1.0-96-g5a2ef36 -c echo Container started
[6407 ms] trap "exit 0" 15
[6408 ms] exec "$@"
[6408 ms] while sleep 1 & wait $!; do :; done -
[6408 ms]     at Tse (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:1946:3264)
[6408 ms]     at rO (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:1946:3200)
[6408 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[6408 ms]     at async Xse (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:1961:2626)
[6408 ms]     at async vh (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:1961:3741)
[6408 ms]     at async gae (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:2092:10213)
[6408 ms]     at async mae (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js:2092:9954)
[6420 ms] Exit code 1
[6424 ms] Command failed: C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.292.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\<user>\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-233e5c9e-48ff-4678-9cf7-9a5260329ce71684749632051 --workspace-folder c:\Users\<user>\Documents\teodor_evo\nodes\autonomy --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\<user>\Documents\teodor_evo\nodes\autonomy --id-label devcontainer.config_file=c:\Users\<user>\Documents\teodor_evo\nodes\autonomy\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\<user>\Documents\teodor_evo\nodes\autonomy\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6424 ms] Exit code 1
```

Any Idea whats causing this? The error message is not very clear to me.

**Comment by jduke-halls** [comment]
Perusing through the Microsoft VSCode issues and found a fix.

It worked for me using the VSCode and VSCode Insiders Build and updating to Dev Containers >= v0.282.0 (tested on v.0.292.0 and v.0.293.0)

Edit your vscode settings.json and add the line:
```"dev.containers.mountWaylandSocket": false```

Alternatively, search your settings for "mountWaylandSocket" and uncheck the box (this will add the directive to your settings.json file)

Source: [https://github.com/microsoft/vscode-remote-release/issues/8306](https://github.com/microsoft/vscode-remote-release/issues/8306)

VSCode Ins

**Comment by dpmerrill** [comment]
This issue has been confirmed on Windows 10 Pro.
The work-arounds mentioned in the comments did not work for me, but they make it look like a Dev Containers extension issue.
The "mounts" configuration setting works fine on Mac (I haven't tried it on other non-WSL platforms).
