### ISSUE TITLE
Rancher Desktop unable to open - EPERM issue

### ISSUE THREAD

**Issue by vamshikrishna83** [rancher-sandbox/rancher-desktop#4830]
### Actual Behavior

Try to restart an existing loaded instance of Rancher Desktop on Windows 11 machine, and this leads to a failure where as the expectation is to get the application UI to start and initialize properly.

### Steps to Reproduce

1. Close an existing instance of Rancher Desktop.
2. Try to restart the application.
3. Expected - Application restarts and initializes properly.
4. Actual - Error

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EPERM: operation not permitted, unlink 'C:\Users\vamshikb\AppData\Local\rancher-desktop\logs\docker.log'
    at Object.unlinkSync (node:fs:1735:3)
    at m (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:6201)
    at Module.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:16:109585)
    at r (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:132)
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:1569
    at Object.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:1580)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)

[OK]

### Result

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EPERM: operation not permitted, unlink 'C:\Users\vamshikb\AppData\Local\rancher-desktop\logs\docker.log'
    at Object.unlinkSync (node:fs:1735:3)
    at m (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:6201)
    at Module.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:16:109585)
    at r (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:132)
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:1569
    at Object.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:1580)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)

[OK]

### Expected Behavior

Rancher Desktop UI to open and initialize properly.

### Rancher Desktop Version

1.8.1

### Rancher Desktop K8s Version

default

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 22H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

Cisco VPN, but not connected when initializing Rancher Desktop

**Comment by vamshikrishna83** [comment]
This issue keeps repeating even after killing all Rancher Desktop processes from Task Manager, and restarting the application.

Only way to get the UI to open up properly as of now, is to reboot the entire system.

**Comment by vamshikrishna83** [comment]
I am not running Rancher Desktop as an administrator.

I have enabled debug mode, and tried to repro the problem - but not able to, as the application doesn't start at all from second time. Bunch of Rancher Desktop processes show up in Task Manager, but no UI or no useful data in Rancher Desktop logs.

I have done factory reset now, and will give it a try for next couple of days to see if the issue persists. Will reach out again, if the issue repeats again.
