### ISSUE TITLE
Can no longer start dev env on Windows 11

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/rancher-desktop#5267]
### Actual Behavior

If I run `yarn dev` on Windows 11, I get the following output:

```
PS C:\Users\user\rancher-desktop> yarn dev
yarn run v1.22.19
$ node scripts/ts-wrapper.js scripts/dev.ts
Hash: 473b8fed9418a9c02824
Version: webpack 4.46.0
Time: 49961ms
Built at: 08/01/2023 11:04:27 AM
         Asset      Size   Chunks                   Chunk Names
    preload.js  28.8 KiB  preload  [emitted]        preload
preload.js.map  41.9 KiB  preload  [emitted] [dev]  preload
Entrypoint preload = preload.js preload.js.map
[./pkg/rancher-desktop/preload/extensions.ts] 20.2 KiB {preload} [built]
[./pkg/rancher-desktop/preload/index.ts] 168 bytes {preload} [built]
[./pkg/rancher-desktop/utils/clone.ts] 306 bytes {preload} [built]
[./pkg/rancher-desktop/utils/ipcRenderer.ts] 196 bytes {preload} [built]
[electron] external "electron" 42 bytes {preload} [built]
[os] external "os" 42 bytes {preload} [built]

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   client-side          │
   │   ▸ Target:      static               │
   │                                       │
   │   Listening: http://localhost:8888/   │
   │                                       │
   ╰───────────────────────────────────────╯

i Preparing project for development                                                                                                                                                                    11:04:33
i Initial build may take a while                                                                                                                                                                       11:04:33
√ Builder initialized                                                                                                                                                                                  11:04:33
√ Nuxt files generated                                                                                                                                                                                 11:04:33

* Client █████████████████████████ building (10%) 1/2 modules 1 active
 node_modules\webpack-hot-middleware\client.js

node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\user\rancher-desktop\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\user\rancher-desktop\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\user\rancher-desktop\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\user\rancher-desktop\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\user\rancher-desktop\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\user\rancher-desktop\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\user\rancher-desktop\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\user\rancher-desktop\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\user\rancher-desktop\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\user\rancher-desktop\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\user\rancher-desktop\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.2.0
C:\Users\user\rancher-desktop\scripts\dev.ts:28
    const newError: Error & { code?: number } = new Error(combinedMessage);
                                                ^
Error: Renderer process error: Process exited with code 1
    at DevRunner.emitError (C:\Users\user\rancher-desktop\scripts\dev.ts:28:49)
    at C:\Users\user\rancher-desktop\scripts\dev.ts:53:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Caused by: Error: Process exited with code 1
    at ChildProcess.<anonymous> (C:\Users\user\rancher-desktop\scripts\lib\build-utils.ts:95:18)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to Reproduce

- Pull the latest main branch from repository
- Run `yarn`
- Run `yarn dev`

### Result

See above

### Expected Behavior

Should open Rancher Desktop dev environment.

### Rancher Desktop Version

latest / main branch

### Rancher Desktop K8s Version

unrelated

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by rak-phillip** [comment]
I haven't been able to repro in my existing Windows 11 VM. I think that I will provision a new VM and test this from a blank slate.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/acc93061-66cb-42a8-9d6d-fba57c08ca58)

**Comment by s0nea** [comment]
I want to give an update on the issue. I did more investigation/testing here until I removed and re-installed everything. And suddenly everything worked out well. I unfortunately can't tell the actual reason but my setup is good for now.

I I'll close the issue for now and re-open it if it happens again.

Thank you @rak-phillip for taking a look!
