### ISSUE TITLE
Kubernetes Error - Error: spawn file ENOENT when starting Rancher Desktop

### ISSUE THREAD

**Issue by aaronvizzini** [rancher-sandbox/rancher-desktop#5314]
### Actual Behavior

When launching Rancher Desktop I am immediately receiving a "Kubernetes Error" and it is failing to start.

### Steps to Reproduce

This problem first started happening after having went to Preferences > Application > Administrative Access and checking the box to "Allow to acquire administrative credentials (sudo access)".

After Rancher Desktop restarted, I began to get this error. Unchecking the box did not resolve the error.

### Result

<img width="756" alt="Screenshot 2023-08-08 at 11 20 46 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/766233/b13adf85-afec-4fcc-8f08-1b618d6a2eff">

<img width="298" alt="Screenshot 2023-08-08 at 11 30 09 PM" src="https://github.com/rancher-sandbox/rancher-desktop/assets/766233/ecd651cb-ef85-42f4-a023-3e2a45ed4d9b">

at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn file',
  path: 'file',
  spawnargs: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura'
  ]
}

### Expected Behavior

I expect Rancher Desktop to launch and Kubernetes not to have errors.

### Additional Information

I've attempted to restart the computer. I've "Reset Kubernetes" and performed a "Factory Reset" multiple times. The issue still occurs. 

**In the diagnostics.log I am seeing:**

2023-08-09T06:18:36.837Z: Running check RD_BIN_IN_BASH_PATH
2023-08-09T06:18:36.838Z: Running check RD_BIN_IN_ZSH_PATH
2023-08-09T06:18:36.838Z: path diagnostics for : error:  TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at new NodeError (node:internal/errors:372:5)
    at normalizeSpawnArguments (node:child_process:517:11)
    at spawn (node:child_process:702:13)
    at l (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:15140)
    at b.check (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/6.js:1:1044)
    at Object.runChecker (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:43:131570)
    at /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:43:130743
    at async i.invoke (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:16015) {
  code: 'ERR_INVALID_ARG_VALUE'
}
2023-08-09T06:18:36.840Z: path diagnostics for : error:  TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at new NodeError (node:internal/errors:372:5)
    at normalizeSpawnArguments (node:child_process:517:11)
    at spawn (node:child_process:702:13)
    at l (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:15140)
    at b.check (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/6.js:1:1044)
    at Object.runChecker (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:43:131570)
    at /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:43:130743
    at async i.invoke (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:16015) {
  code: 'ERR_INVALID_ARG_VALUE'
}

**In the background.log I am seeing:**

2023-08-09T06:18:36.692Z: mainEvents settings-update: {"version":8,"application":{"adminAccess":false,"debug":true,"extensions":{"allowed":{"enabled":false,"list":[]}},"pathManagementStrategy":"rcfiles","telemetry":{"enabled":true},"updater":{"enabled":false},"autoStart":true,"startInBackground":true,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"name":"moby"},"virtualMachine":{"memoryInGB":6,"numberCPUs":4,"hostResolver":true},"WSL":{"integrations":{}},"kubernetes":{"version":"1.26.7","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"diagnostics":{"showMuted":false,"mutedChecks":{}},"extensions":{},"experimental":{"virtualMachine":{"type":"qemu","useRosetta":false,"socketVMNet":false,"mount":{"type":"reverse-sshfs","9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap","msizeInKB":128}},"networkingTunnel":false,"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":""}}}}
2023-08-09T06:18:36.833Z: Checking if credential helper osxkeychain is working...
2023-08-09T06:18:36.954Z: Credential helper docker-credential-osxkeychain is working.
2023-08-09T06:18:36.988Z: Kubernetes was unable to start: Error: spawn file ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn file',
  path: 'file',
  spawnargs: [
    '/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl.ventura'
  ]
}
2023-08-09T06:18:39.371Z: ipcMain: "k8s-state" triggered with arguments: 
2023-08-09T06:18:39.575Z: ipcMain: "get-app-version" triggered with arguments: 
2023-08-09T06:21:22.939Z: ipcMain: "show-logs" triggered with arguments: 

### Rancher Desktop Version

1.9.1

### Rancher Desktop K8s Version

1.27.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

macOS Ventura 13.5

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by pshutt97** [comment]
I've hit this before and had to go into Activity Monitor, search for limactl.ventura and then kill the task.

**Comment by aaronvizzini** [comment]
> I've hit this before and had to go into Activity Monitor, search for limactl.ventura and then kill the task.

I'm not seeing it in the list of processes.

**Comment by adamkpickering** [comment]
I'm waiting on a machine to try to repro this, but in the meantime, what happens if you reinstall?

**Comment by aaronvizzini** [comment]
> I'm waiting on a machine to try to repro this, but in the meantime, what happens if you reinstall?

If by reinstall you mean just delete the app file and download a new one. That didn't seem to make a difference. And trying to run in from a different user account didn't help either.

**Comment by aaronvizzini** [comment]
I'm not sure if it's related to this issue but it feels related... I went to re-install Eclipse on this same computer, after this problem started and now I'm seeing this error which I've not seen before:

"java.io.IOException: Cannot run program "chmod": error=2, No such file or directory"

I'm seeing chmod in the /bin ...

**Comment by adamkpickering** [comment]
Do you have jamf or something similar installed? This sounds like the type of issue that kind of software typically causes.

**Comment by aaronvizzini** [comment]
> Do you have jamf or something similar installed? This sounds like the type of issue that kind of software can cause.

There's Addigy , would that be along the same lines of software you're thinking of?

**Comment by adamkpickering** [comment]
Looks similar. If it was just Rancher Desktop you were having an issue with I'd say there's a decent chance it's a Rancher Desktop problem. But issues with two applications plus Addigy smells like IT locking a system down.

Are you able to get a colleague with a managed system to install the same applications, to see if they have the same problem?

If you have a system without Addigy, does the issue appear there?

**Comment by aaronvizzini** [comment]
I was able to install Eclipse previously without issue. So it does sound plausible that having Addigy + changing the above mentioned Rancher Desktop setting put it into a weird state that I'm now stuck in. 

There's only one other team member and they wouldn't want to risk getting put into the same issue. I can see if it's possible to somehow temporarily disable Addigy and see if that clears up anything, not sure.

**Comment by aaronvizzini** [comment]
One last update that'll probably get Rancher Desktop off the hook. 

My personal laptop is also a Macbook Pro, a slightly different processor but still an Apple Silicon (non-intel) one with the same OS version.

I partitioned my HD and installed a fresh OS. Replicated my steps on this laptop, and no issues were encountered.

I can only assume that it is indeed MDM Software/Addigy that is causing interference. Thanks for your time with this.

**Comment by adamkpickering** [comment]
I'm glad to hear your issue is resolved. If the problem reappears, comment here and we can reopen this issue :smile:
