### ISSUE TITLE
Error Starting Kubernetes - limactl exited with code 1

### ISSUE THREAD

**Issue by vmoutoussamy** [rancher-sandbox/rancher-desktop#532]
I'm getting this issue when trying Rancher Desktop on macOS Big Sur. Any ideas how to troubleshoot? is there a way to retrieve more information? limatcl has a debug options but I don't know how to tell Rancher Desktop to use it...

![Screenshot 2021-08-23 at 16 28 14](https://user-images.githubusercontent.com/3873925/130464804-941b9335-ceb4-4a6f-a257-55beece78bc3.png)

**Comment by vmoutoussamy** [comment]
# cat lima.log                                                                                                                                                     
time="2021-08-23T16:28:02+02:00" level=info msg="Using the existing instance \"rancher-desktop\""
time="2021-08-23T16:28:02+02:00" level=warning msg="expected status \"Stopped\", got \"Broken\""
time="2021-08-23T16:28:02+02:00" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.log\")"
time="2021-08-23T16:28:02+02:00" level=info msg="SSH Local Port: 60705"
time="2021-08-23T16:28:02+02:00" level=error msg="[hostagent] couldn't remove existing localhost host keys"
time="2021-08-23T16:28:02+02:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/ha.stderr.log\")"
Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:3150)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by vmoutoussamy** [comment]
Why are you guys using this folder "/Users/[username]/Library/State/rancher-desktop/logs" ? Why not using the existing folder "/Users/[username]/Library/Application\ Support/rancher-desktop/" and create a "logs" folder in it?

**Comment by kiranchavala** [comment]
Hi Are you on M1 mac with ARM ?

**Comment by mook-as** [comment]
The folders we currently use are dumb (and are an artifact of some packages we used), and will be fixed for #298. The proper place for logs (on macOS) is actually `~/Library/Logs`; see that issue for details if you want them (I believe it would also mean you can browse it via Console.app).

As for your error starting, please check `/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/ha.stderr.log` as prompted in the logs you pasted?

**Comment by jandubois** [comment]
`ha.stderr.log` will have more details, but I'm sure this is a variant of #504, i.e. some error in your `~/.ssh/known_hosts` file.

**Comment by vmoutoussamy** [comment]
Sorry I forgot to mention: MacBook Pro (16-inch, 2019) 2,6 GHz 6-Core Intel Core i7.
I don't have ha.stderr.log.
# pwd                                                                                                                                                              
/Users/gb/Library/State/rancher-desktop/logs
# ls -ls
total 12
4 -rw------- 1 gb staff  763 Aug 23 16:48 background.log
4 -rw------- 1 gb staff  331 Aug 23 16:28 k8s.log
0 -rw------- 1 gb staff    0 Aug 23 16:27 kim.log
4 -rw------- 1 gb staff 1176 Aug 23 16:28 lima.log
0 -rw------- 1 gb staff    0 Aug 23 16:27 settings.log
0 -rw------- 1 gb staff    0 Aug 23 16:27 update.log
0 -rw------- 1 gb staff    0 Aug 23 16:27 wsl.log

**Comment by vmoutoussamy** [comment]
After cleaning up my ~/.ssh/known_hosts, I now have the following error:

> {"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.log\")","time":"2021-08-24T10:28:11+02:00"}
> {"level":"debug","msg":"qCmd.Args: [/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/qemu-system-x86_64 -cpu Haswell-v4 -machine q35,accel=hvf -smp 2,sockets=1,cores=2,threads=1 -m 6144 -boot order=d,splash-time=0,menu=on -drive file=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/basedisk,media=cdrom,readonly=on -drive file=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/diffdisk,if=virtio -cdrom /Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:64548-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:66:ca:f6 -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.sock,server,nowait,logfile=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/qmp.sock,server,nowait -qmp chardev:char-qmp -name lima-rancher-desktop -pidfile /Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/qemu.pid]","time":"2021-08-24T10:28:11+02:00"}
> {"level":"info","msg":"Waiting for the essential requirement 1 of 4: \"ssh\"","time":"2021-08-24T10:28:11+02:00"}
> {"level":"debug","msg":"executing script \"ssh\"","time":"2021-08-24T10:28:12+02:00"}
> {"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 64548: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 64548: Connection refused\\r\\n\": exit status 255","time":"2021-08-24T10:28:12+02:00"}
> {"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: -chardev socket,id=char-serial,path=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.sock,server,nowait,logfile=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.log: warning: short-form boolean option 'server' deprecated","time":"2021-08-24T10:28:12+02:00"}
> {"level":"debug","msg":"qemu[stderr]: Please use server=on instead","time":"2021-08-24T10:28:12+02:00"}
> {"error":"signal: abort trap","level":"info","msg":"QEMU has exited","time":"2021-08-24T10:28:12+02:00"}
> {"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: -chardev socket,id=char-serial,path=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.sock,server,nowait,logfile=/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/serial.log: warning: short-form boolean option 'nowait' deprecated","time":"2021-08-24T10:28:12+02:00"}
> {"level":"debug","msg":"qemu[stderr]: Please use wait=off instead","time":"2021-08-24T10:28:12+02:00"}
> signal: abort trap

**Comment by vmoutoussamy** [comment]
I tried the commands on https://github.com/rancher-sandbox/rancher-desktop/issues/535 and I have the same output as https://github.com/rancher-sandbox/rancher-desktop/issues/535#issuecomment-904644158 with using the port 61370

> /usr/bin/ssh -p 61370 -vvvv -i ~/Library/State/rancher-desktop/lima/_config/user -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -F /dev/null -l $USER -t 127.0.0.1 
> OpenSSH_8.1p1, LibreSSL 2.7.3
> debug1: Reading configuration data /dev/null
> debug2: resolve_canonicalize: hostname 127.0.0.1 is address
> debug2: ssh_connect_direct
> debug1: Connecting to 127.0.0.1 [127.0.0.1] port 61370.
> debug1: connect to address 127.0.0.1 port 61370: Connection refused
> ssh: connect to host 127.0.0.1 port 61370: Connection refused

> /usr/bin/ssh -p 61370 -vvvv -i ~/Library/State/rancher-desktop/lima/_config/user -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -F /dev/null -l $USER -o ControlMaster=auto -o ControlPath=~/Library/State/rancher-desktop/lima/rancher-desktop/ssh.sock -o ControlPersist=5m -t 127.0.0.1 
> OpenSSH_8.1p1, LibreSSL 2.7.3
> debug1: Reading configuration data /dev/null
> debug2: resolve_canonicalize: hostname 127.0.0.1 is address
> debug1: auto-mux: Trying existing master
> debug1: Control socket "/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/ssh.sock" does not exist
> debug2: ssh_connect_direct
> debug1: Connecting to 127.0.0.1 [127.0.0.1] port 61370.
> debug1: connect to address 127.0.0.1 port 61370: Connection refused
> ssh: connect to host 127.0.0.1 port 61370: Connection refused

**Comment by mook-as** [comment]
```json
{"error":"signal: abort trap","level":"info","msg":"QEMU has exited","time":"2021-08-24T10:28:12+02:00"}
```
So qemu is aborting somehow… @jandubois any ideas? 

The logs would be in `/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/` (`ha.stdout.log`, `ha.stderr.log`, and `serial.log`); however, depending on where qemu is aborting it may or may not have interesting things.

**Comment by jandubois** [comment]
If QEMU aborts, then the `ssh` problems are no longer important because there won't be an `sshd` daemon to connect to.

I have 2 thoughts about the "abort trap". My first thought was that somehow the code signature on the qemu binary got lost. But if I manually remove it, macOS will not even start Rancher Desktop, but claim that it is damaged, so I doubt this is the issue.

My other though is that it is a QEMU bug related to the cpu. There are known issues with modern cpus and `-cpu host`, which is why Lima hardcodes the cpu to `Haswell-v4`.

Let's try to isolate this by just running qemu and see if it reproduces the "abort trap". This is a slightly simplified qemu setup that will use the RD iso and hardware settings:

```
#!/bin/sh
cd "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin"
export PATH="$PWD/lima/bin:$PATH"
qemu-system-x86_64 \
    -boot order=d,splash-time=0,menu=on \
    -cdrom "$PWD/alpline-lima-v0.1.0-std-3.13.5.iso" \
    -cpu Haswell-v4 \
    -smp 4,sockets=1,cores=4,threads=1 \
    -m 6144 \
    -net nic,model=virtio \
    -net user,net=192.168.5.0/24,hostfwd=tcp:127.0.0.1:20022-:22 \
    -display cocoa \
    -device virtio-rng-pci \
    -device virtio-vga \
    -device virtio-keyboard-pci \
    -device virtio-mouse-pci \
    -parallel none
```

If this fails the same way, try different values for `-cpu`. I would try `-cpu host` first, and then `-cpu Skylake-Client` or `-cpu IceLake-Client` (not sure which arch your CPU corresponds to).

Let's see what happens before looking deeper into QEMU CPU issues...

**Comment by jandubois** [comment]
> try different values for `-cpu`

If all of these fail, try a really old CPU, like `-cpu Penryn`.

**Comment by vmoutoussamy** [comment]
> If QEMU aborts, then the `ssh` problems are no longer important because there won't be an `sshd` daemon to connect to.
> 
> I have 2 thoughts about the "abort trap". My first thought was that somehow the code signature on the qemu binary got lost. But if I manually remove it, macOS will not even start Rancher Desktop, but claim that it is damaged, so I doubt this is the issue.
> 
> My other though is that it is a QEMU bug related to the cpu. There are known issues with modern cpus and `-cpu host`, which is why Lima hardcodes the cpu to `Haswell-v4`.
> 
> Let's try to isolate this by just running qemu and see if it reproduces the "abort trap". This is a slightly simplified qemu setup that will use the RD iso and hardware settings:
> 
> ```
> #!/bin/sh
> cd "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin"
> export PATH="$PWD/lima/bin:$PATH"
> qemu-system-x86_64 \
>     -boot order=d,splash-time=0,menu=on \
>     -cdrom "$PWD/alpline-lima-v0.1.0-std-3.13.5.iso" \
>     -cpu Haswell-v4 \
>     -smp 4,sockets=1,cores=4,threads=1 \
>     -m 6144 \
>     -net nic,model=virtio \
>     -net user,net=192.168.5.0/24,hostfwd=tcp:127.0.0.1:20022-:22 \
>     -display cocoa \
>     -device virtio-rng-pci \
>     -device virtio-vga \
>     -device virtio-keyboard-pci \
>     -device virtio-mouse-pci \
>     -parallel none
> ```

I feel like this is working well:
![Screenshot 2021-08-25 at 16 30 53](https://user-images.githubusercontent.com/3873925/130809891-82f7e8d2-9b3a-4a4e-b6a3-fa18feff665a.png)

I just used the script above and launch it.

> If this fails the same way, try different values for `-cpu`. I would try `-cpu host` first, and then `-cpu Skylake-Client` or `-cpu IceLake-Client` (not sure which arch your CPU corresponds to).
> 
> Let's see what happens before looking deeper into QEMU CPU issues...

**Comment by vmoutoussamy** [comment]
> ```json
> {"error":"signal: abort trap","level":"info","msg":"QEMU has exited","time":"2021-08-24T10:28:12+02:00"}
> ```
> 
> So qemu is aborting somehow… @jandubois any ideas?
> 
> The logs would be in `/Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/` (`ha.stdout.log`, `ha.stderr.log`, and `serial.log`); however, depending on where qemu is aborting it may or may not have interesting things.

[ha.stderr.log](https://github.com/rancher-sandbox/rancher-desktop/files/7047727/ha.stderr.log)
[ha.stdout.log](https://github.com/rancher-sandbox/rancher-desktop/files/7047728/ha.stdout.log)

Funny enough I don't have serial.log...
ls /Users/gb/Library/State/rancher-desktop/lima/rancher-desktop/                                                                        
basedisk  cidata.iso  diffdisk  ha.stderr.log  ha.stdout.log  lima.yaml  qemu.pid

**Comment by olemaiwald** [comment]
Has anyone tried to follow the described procedure with an M1 Mac?

I have modified the above commands slightly, but it does not seem to resolve the issue.

**Comment by mercer** [comment]
I see this issue with rancher `1.1.1` macos 12.3 (21E230)

```
time="2022-03-22T11:14:32+02:00" level=info msg="Using the existing instance \"0\""
time="2022-03-22T11:14:32+02:00" level=info msg="Starting switch daemon for \"shared\" network"
time="2022-03-22T11:14:32+02:00" level=fatal msg="\"/private/var/run/rancher-desktop-lima\" doesn't seem to be writable by the daemon (gid:1) group"
2022-03-22T09:14:32.065Z: + limactl start --tty=false 0
2022-03-22T09:14:32.071Z: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
2022-03-22T09:14:32.073Z: Error starting lima: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:8692)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

<img width="887" alt="image" src="https://user-images.githubusercontent.com/95358/159447316-b76b99d1-9e0b-435a-a4c7-957746395174.png">

**Comment by dsldiesel** [comment]
Exactly same issue as @mercer with Rancher 1.1.1 and osx 12.3 on macbook pro with M1 arch.
What's the fix?

**Comment by mercer** [comment]
The solution was hinted in `update.log` linking to https://github.com/rancher-sandbox/rancher-desktop/issues/1815#issuecomment-1068522900 

This workarond solved the problem for me.

**Comment by ohare93** [comment]
I am now getting this same error. The above linked fix did not resolve it. I am not on an M1, but a MacBook Pro 2019. Lastly this issue started occurring with no warning: everything was running fine before, and I did no restart / update of Rancher, or even my laptop!

<img width="749" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/1471350/396abb41-e5f6-4a70-ada0-69bbb40e958b">

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/1471350/fe938322-03c1-4f0e-919b-7c11eaeefbb3)

The weird thing here is: I have Kubernetes disabled! Always have 😅 

<img width="823" alt="image" src="https://github.com/rancher-sandbox/rancher-desktop/assets/1471350/115c09b3-f053-4230-936b-03ad0886b6f1">


Things I have tried:
- The above linked fix
    - >The solution was hinted in update.log linking to https://github.com/rancher-sandbox/rancher-desktop/issues/1815#issuecomment-1068522900
- Enabling and disabling Kubernetes
- Restarting
    - Rancher Desktop
    - My laptop

Any help? 🤷‍♂️

**Comment by ohare93** [comment]
Nevermind, I was out of memory on the vm. These steps https://github.com/rancher-sandbox/rancher-desktop/issues/1521#issuecomment-1030886234 fixed it for me 👍
