### ISSUE TITLE
ubuntu22.04 rancher-desktop won't start

### ISSUE THREAD

**Issue by shifengbin** [rancher-sandbox/rancher-desktop#5550]
### Actual Behavior

click icon then cause error

### Steps to Reproduce

click rancher-desktop icon

### Result

Kubernetes Error
Rancher Desktop 1.10.0 - linux (x64)
Error Starting Kubernetes
Error: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
Last command run:
/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false 0

Context:
Starting virtual machine

Some recent [logfile](app://./index.html#) lines:
    'time="2023-09-20T15:23:59+08:00" level=info msg="[hostagent] Shutting down the host agent"\n' +
    'time="2023-09-20T15:23:59+08:00" level=warning msg="[hostagent] failed to exit SSH master"\n' +
    'time="2023-09-20T15:23:59+08:00" level=info msg="[hostagent] Shutting down QEMU with ACPI"\n' +
    'time="2023-09-20T15:23:59+08:00" level=warning msg="[hostagent] failed to open the QMP socket \\"/home/shifengbin/.local/share/rancher-desktop/lima/0/qmp.sock\\", forcibly killing QEMU"\n' +
    'time="2023-09-20T15:23:59+08:00" level=info msg="[hostagent] QEMU has already exited"\n' +
    'time="2023-09-20T15:23:59+08:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \\"/home/shifengbin/.local/share/rancher-desktop/lima/0/ha.stderr.log\\")"\n',
  code: 1,
  [Symbol(child-process.command)]: '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false 0'
}

### Expected Behavior

can start

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

1.27.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

Ubuntu 22.04.3 LTS

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by shifengbin** [comment]
/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false 0

INFO[0000] Using the existing instance "0"              
INFO[0000] Attempting to download the nerdctl archive    arch=x86_64 digest="sha256:3bb5f5358ee2c3bd9097e0bf37649c1775e2449094e75acf629f129ec2c7915f" location="https://github.com/containerd/nerdctl/releases/download/v1.4.0/nerdctl-full-1.4.0-linux-amd64.tar.gz"
INFO[0000] Using cache "/home/shifengbin/.cache/lima/download/by-url-sha256/7f7d5c10ef2e2b350e26ceca17d2e3a7ce9993c867ce53f0a1114aa0264bfb4b/data" 
INFO[0000] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/home/shifengbin/.lima/0/serial.log") 
INFO[0000] SSH Local Port: 43875                        
INFO[0000] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0000] [hostagent] Driver stopped due to error: "exit status 1" 
INFO[0000] [hostagent] Shutting down the host agent     
WARN[0000] [hostagent] failed to exit SSH master        
INFO[0000] [hostagent] Shutting down QEMU with ACPI     
WARN[0000] [hostagent] failed to open the QMP socket "/home/shifengbin/.lima/0/qmp.sock", forcibly killing QEMU 
INFO[0000] [hostagent] QEMU has already exited          
FATA[0000] exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/home/shifengbin/.lima/0/ha.stderr.log")


{"level":"debug","msg":"executing ssh for exiting the master: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/home/shifengbin/.lima/_config/user\" -o IdentityFile=\"/home/shifengbin/.ssh/id_ed25519\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=shifengbin -o ControlMaster=auto -o ControlPath=\"/home/shifengbin/.lima/0/ssh.sock\" -o ControlPersist=5m -O exit -p 43875 127.0.0.1]","time":"2023-09-20T16:15:53+08:00"}
{"error":"failed to execute `ssh -O exit -p 43875 127.0.0.1`, out=\"Control socket connect(/home/shifengbin/.lima/0/ssh.sock): No such file or directory\\r\\n\": exit status 255","level":"warning","msg":"failed to exit SSH master","time":"2023-09-20T16:15:53+08:00"}
{"level":"info","msg":"Shutting down QEMU with ACPI","time":"2023-09-20T16:15:53+08:00"}
{"error":"dial unix /home/shifengbin/.lima/0/qmp.sock: connect: connection refused","level":"warning","msg":"failed to open the QMP socket \"/home/shifengbin/.lima/0/qmp.sock\", forcibly killing QEMU","time":"2023-09-20T16:15:53+08:00"}
{"level":"info","msg":"QEMU has already exited","time":"2023-09-20T16:15:53+08:00"}

**Comment by shifengbin** [comment]
2023-09-20T08:36:11.403Z: Rejected cert expired on Fri, 03 Mar 2023 12:09:48 GMT issued by E-Tugra Certification Authority
2023-09-20T08:36:11.406Z: Rejected cert expired on Mon, 15 May 2023 04:52:29 GMT issued by Hongkong Post Root CA 1
2023-09-20T08:36:11.436Z: mainEvents settings-update: {"version":9,"application":{"adminAccess":false,"debug":false,"extensions":{"allowed":{"enabled":false,"list":[]},"installed":{}},"pathManagementStrategy":"rcfiles","telemetry":{"enabled":true},"updater":{"enabled":false},"autoStart":false,"startInBackground":false,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"name":"moby"},"virtualMachine":{"memoryInGB":6,"numberCPUs":2,"hostResolver":true},"WSL":{"integrations":{}},"kubernetes":{"version":"","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"diagnostics":{"showMuted":false,"mutedChecks":{}},"experimental":{"virtualMachine":{"type":"qemu","useRosetta":false,"socketVMNet":false,"mount":{"type":"reverse-sshfs","9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap"}},"networkingTunnel":false,"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":"","noproxy":["0.0.0.0/8","10.0.0.0/8","127.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.168.0.0/16","224.0.0.0/4","240.0.0.0/4"]}}}}
2023-09-20T08:36:37.530Z: mainEvents settings-update: {"version":9,"application":{"adminAccess":false,"debug":false,"extensions":{"allowed":{"enabled":false,"list":[]},"installed":{}},"pathManagementStrategy":"rcfiles","telemetry":{"enabled":true},"updater":{"enabled":false},"autoStart":false,"startInBackground":false,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"name":"moby"},"virtualMachine":{"memoryInGB":6,"numberCPUs":2,"hostResolver":true},"WSL":{"integrations":{}},"kubernetes":{"version":"1.27.5","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"diagnostics":{"showMuted":false,"mutedChecks":{}},"experimental":{"virtualMachine":{"type":"qemu","useRosetta":false,"socketVMNet":false,"mount":{"type":"reverse-sshfs","9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap"}},"networkingTunnel":false,"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":"","noproxy":["0.0.0.0/8","10.0.0.0/8","127.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.168.0.0/16","224.0.0.0/4","240.0.0.0/4"]}}}}
2023-09-20T08:36:37.533Z: mainEvents settings-update: {"version":9,"application":{"adminAccess":false,"debug":false,"extensions":{"allowed":{"enabled":false,"list":[]},"installed":{}},"pathManagementStrategy":"rcfiles","telemetry":{"enabled":true},"updater":{"enabled":false},"autoStart":false,"startInBackground":false,"hideNotificationIcon":false,"window":{"quitOnClose":false}},"containerEngine":{"allowedImages":{"enabled":false,"patterns":[]},"name":"moby"},"virtualMachine":{"memoryInGB":6,"numberCPUs":2,"hostResolver":true},"WSL":{"integrations":{}},"kubernetes":{"version":"1.27.5","port":6443,"enabled":true,"options":{"traefik":true,"flannel":true},"ingress":{"localhostOnly":false}},"portForwarding":{"includeKubernetesServices":false},"images":{"showAll":true,"namespace":"k8s.io"},"diagnostics":{"showMuted":false,"mutedChecks":{}},"experimental":{"virtualMachine":{"type":"qemu","useRosetta":false,"socketVMNet":false,"mount":{"type":"reverse-sshfs","9p":{"securityModel":"none","protocolVersion":"9p2000.L","msizeInKib":128,"cacheMode":"mmap"}},"networkingTunnel":false,"proxy":{"enabled":false,"address":"","password":"","port":3128,"username":"","noproxy":["0.0.0.0/8","10.0.0.0/8","127.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.168.0.0/16","224.0.0.0/4","240.0.0.0/4"]}}}}
2023-09-20T08:36:37.626Z: UnhandledRejectionWarning: Error: ENOENT: no such file or directory, watch '/home/shifengbin/.kube/config'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at /opt/rancher-desktop/resources/app.asar/dist/app/background.js:43:102279
    at Array.map (<anonymous>)
    at Js.watchForChanges (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:43:102268) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/home/shifengbin/.kube/config',
  filename: '/home/shifengbin/.kube/config'
}
2023-09-20T08:36:38.521Z: Kubernetes was unable to start: c [Error]: /opt/rancher-desktop/resources/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/opt/rancher-desktop/resources/app.asar/dist/app/background.js:1:9554)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  command: [
    '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl',
    'start',
    '--tty=false',
    '/home/shifengbin/.local/share/rancher-desktop/lima/_config/0.yaml'
  ],
  stdout: '',
  stderr: 'time="2023-09-20T16:36:37+08:00" level=info msg="Terminal is not available, proceeding without opening an editor"\n' +
    'time="2023-09-20T16:36:37+08:00" level=info msg="Attempting to download the image" arch=x86_64 digest= location=/opt/rancher-desktop/resources/resources/linux/alpine-lima-v0.2.31.rd6-rd-3.18.0.iso\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="Downloaded the image from \\"/opt/rancher-desktop/resources/resources/linux/alpine-lima-v0.2.31.rd6-rd-3.18.0.iso\\""\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \\"/home/shifengbin/.local/share/rancher-desktop/lima/0/serial.log\\")"\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="SSH Local Port: 37689"\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \\"ssh\\""\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] Driver stopped due to error: \\"exit status 1\\""\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] Shutting down the host agent"\n' +
    'time="2023-09-20T16:36:38+08:00" level=warning msg="[hostagent] failed to exit SSH master"\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] Shutting down QEMU with ACPI"\n' +
    'time="2023-09-20T16:36:38+08:00" level=warning msg="[hostagent] failed to open the QMP socket \\"/home/shifengbin/.local/share/rancher-desktop/lima/0/qmp.sock\\", forcibly killing QEMU"\n' +
    'time="2023-09-20T16:36:38+08:00" level=info msg="[hostagent] QEMU has already exited"\n' +
    'time="2023-09-20T16:36:38+08:00" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \\"/home/shifengbin/.local/share/rancher-desktop/lima/0/ha.stderr.log\\")"\n',
  code: 1,
  [Symbol(child-process.command)]: '/opt/rancher-desktop/resources/resources/linux/lima/bin/limactl start --tty=false /home/shifengbin/.local/share/rancher-desktop/lima/_config/0.yaml'
}

**Comment by shifengbin** [comment]
I know why because I opened the VirtualBox, the two may have conflict
