### ISSUE TITLE
RDX: Error installing the extension `gefyra/docker-desktop-extension:latest`

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop#5591]
I ran into the below error while installing an extension.

```
>rdctl extension install gefyra/docker-desktop-extension:latest
The image gefyra/docker-desktop-extension:latest failed to install: Could not copy host binary /windows/lib/pythonwin/pywin/scintilla/bindings.py
{"message":"422 Unprocessable Entity"}
```

**Log messages from extensions.log**

```
Loaded image: ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest
2023-09-26T16:05:38.310Z: Failed to install extension gefyra/docker-desktop-extension, cleaning up: E [Error]: Could not copy host binary /windows/lib/pythonwin/pywin/scintilla/bindings.py
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:4980
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 211)
    at async j.installHostExecutables (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:4848)
    at async j.install (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:2832)
    at async ra.installExtension (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:148185)
    at async os.installExtension (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:81628) {
  cause: c [Error]: wsl.exe exited with code 1
      at ChildProcess.<anonymous> (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:1:9554)
      at ChildProcess.emit (node:events:527:28)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
    command: [
      'wsl.exe',
      '--distribution',
      'rancher-desktop',
      '--exec',
      '/bin/sh',
      '-c',
      "/usr/bin/docker cp 'e615025f4e6e5515e03df2a3d72ba8f22f75fe444818679ee492b60338967a0f:/windows/lib/pythonwin/pywin/scintilla/bindings.py' - > ''"
    ],
    code: 1,
    [Symbol(child-process.command)]: "wsl.exe --distribution rancher-desktop --exec /bin/sh -c /usr/bin/docker cp 'e615025f4e6e5515e03df2a3d72ba8f22f75fe444818679ee492b60338967a0f:/windows/lib/pythonwin/pywin/scintilla/bindings.py' - > ''"
  },
  code: 1,
  [Symbol(extension-error)]: 0
}
```

**Comment by gunamata** [comment]
Interestingly, the same command throws a different error message when tried on a different occasion (I think this happens after a factor reset)

```
Loaded image: ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest
2023-09-27T04:11:14.141Z: Image gefyra/docker-desktop-extension:latest is allowed to install: undefined
2023-09-27T04:11:25.560Z: Failed to install extension gefyra/docker-desktop-extension, cleaning up: E [Error]: Could not copy host binary /windows/lib/pythonwin/pywin/dialogs/__pycache__/list.cpython-39.pyc
    at C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:4980
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 103)
    ... 3 lines matching cause stack trace ...
    at async os.installExtension (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:81628) {
  cause: Error: Failed to create container gefyra/docker-desktop-extension:latest
      at Kn.makeContainer (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:31:136717)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Kn.copyFile (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:31:137434)
      at async C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:4886
      at async Promise.all (index 103)
      at async j.installHostExecutables (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:4848)
      at async j.install (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\0.js:1:2832)
      at async ra.installExtension (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:148185)
      at async os.installExtension (C:\Program Files\Rancher Desktop\resources\app.asar\dist\app\background.js:43:81628),
  code: 1,
  [Symbol(extension-error)]: 0
}
2023-09-27T04:12:10.622Z: Failed to cleanup extension directory C:\Users\GunasekharMatamalam\AppData\Local\rancher-desktop\extensions\Z2VmeXJhL2RvY2tlci1kZXNrdG9wLWV4dGVuc2lvbg [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\GunasekharMatamalam\AppData\Local\rancher-desktop\extensions\Z2VmeXJhL2RvY2tlci1kZXNrdG9wLWV4dGVuc2lvbg\bin\lib\__pycache__'] {
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\GunasekharMatamalam\\AppData\\Local\\rancher-desktop\\extensions\\Z2VmeXJhL2RvY2tlci1kZXNrdG9wLWV4dGVuc2lvbg\\bin\\lib\\__pycache__'
}
```

As this error message points at issues removing folders, may be this can be addressed by adding `force: true` and/or `maxRetries: 10` to the function call on this [line](https://github.com/rancher-sandbox/rancher-desktop/blob/main/pkg/rancher-desktop/main/extensions/extensions.ts#L241).
