### ISSUE TITLE
local-path-provisioner CrashLoopBackoff

### ISSUE THREAD

**Issue by edrandall** [rancher-sandbox/rancher-desktop#5896]
### Actual Behavior

Pod `kube-system/local-path-provisioner-76d776f6f9-snbth:local-path-provisioner` is in CrashLoopBackoff.

Image: rancher/local-path-provisioner:v0.0.24

### Steps to Reproduce

Havn't particularly done anything and not sure that I'm even using this component.
But after starting rd, it's in this crash state.

Machine: MacBook M2 Pro
MacOS 13.6.1

rdctl list-settings:
{
  "version": 9,
  "application": {
    "adminAccess": true,
    "debug": true,
    "extensions": {
      "allowed": {
        "enabled": false,
        "list": []
      },
      "installed": {}
    },
    "pathManagementStrategy": "manual",
    "telemetry": {
      "enabled": true
    },
    "updater": {
      "enabled": false
    },
    "autoStart": false,
    "startInBackground": false,
    "hideNotificationIcon": false,
    "window": {
      "quitOnClose": false
    }
  },
  "containerEngine": {
    "allowedImages": {
      "enabled": false,
      "patterns": []
    },
    "name": "moby"
  },
  "virtualMachine": {
    "memoryInGB": 16,
    "numberCPUs": 6,
    "hostResolver": true
  },
  "WSL": {
    "integrations": {}
  },
  "kubernetes": {
    "version": "1.26.5",
    "port": 6443,
    "enabled": true,
    "options": {
      "traefik": false,
      "flannel": true
    },
    "ingress": {
      "localhostOnly": false
    }
  },
  "portForwarding": {
    "includeKubernetesServices": false
  },
  "images": {
    "showAll": true,
    "namespace": "k8s.io"
  },
  "diagnostics": {
    "showMuted": true,
    "mutedChecks": {}
  },
  "experimental": {
    "virtualMachine": {
      "type": "vz",
      "useRosetta": true,
      "socketVMNet": true,
      "mount": {
        "type": "reverse-sshfs",
        "9p": {
          "securityModel": "none",
          "protocolVersion": "9p2000.L",
          "msizeInKib": 128,
          "cacheMode": "mmap"
        }
      },
      "networkingTunnel": false,
      "proxy": {
        "enabled": false,
        "address": "",
        "password": "",
        "port": 3128,
        "username": "",
        "noproxy": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "127.0.0.0/8",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.168.0.0/16",
          "224.0.0.0/4",
          "240.0.0.0/4"
        ]
      }
    }
  }
}

### Result

Logs:
```
panic: mismatching message name: got openapi.v2.Header, want

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc({0x12b5d80, 0x104a2a0}, {0x109e981, 0x11})
	/go/src/github.com/rancher/local-path-provisioner/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:147 +0x530
google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo({0x12b5d80, 0x104a2a0}, {0x109e981, 0x11})
	/go/src/github.com/rancher/local-path-provisioner/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:56 +0xa0
google.golang.org/protobuf/internal/impl.legacyLoadMessageType({0x12b5d80, 0x104a2a0}, {0x109e981, 0x11})
	/go/src/github.com/rancher/local-path-provisioner/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:40 +0xdc
google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf({}, {0x126a660, 0x0}, {0x109e981, 0x11})
	/go/src/github.com/rancher/local-path-provisioner/vendor/google.golang.org/protobuf/internal/impl/legacy_export.go:33 +0x9c
github.com/golang/protobuf/proto.RegisterType({0x126a660, 0x0}, {0x109e981, 0x11})
	/go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/protobuf/proto/registry.go:180 +0x40
github.com/googleapis/gnostic/openapiv2.init.0()
	/go/src/github.com/rancher/local-path-provisioner/vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.pb.go:4977 +0x24c
```

### Expected Behavior

not to crash.

### Rancher Desktop Version

1.10.0

### Rancher Desktop K8s Version

1.26.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

macOS

### Operating System / Build Version

Ventura 13.6.1

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by edrandall** [comment]
I _suspect_ that this may have stemmed from my docker image cache becoming populated with a mixture of arm64 and amd64 images.   Since I did a factory reset and set `export DOCKER_DEFAULT_PLATFORM=linux/amd64` to keep everything consistent, I havn't had the problem.
