### ISSUE TITLE
Trying to launch Rancher Desktop with snapshot operation in progress causes an error in startup

### ISSUE THREAD

**Issue by IsaSih** [rancher-sandbox/rancher-desktop#6163]
### Actual Behavior

Trying to launch Rancher Desktop with snapshot operation in progress via CLI causes an error in the application start-up. 

### Steps to Reproduce

1. Shutdown Rancher Desktop
2. From the CLI, run `rdctl snapshot create ABC`
3. Start the application while the operation is still IN PROGRESS

### Result

When snapshot operation is complete and the VM restarts, it fails.

Fatal error:

```

wsl.exe --distribution rancher-desktop --exec cp /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/internal/trivy /usr/local/bin/trivy

Registered distributions: Ubuntu,rancher-desktop-data,rancher-desktop
2023-12-08T19:31:09.087Z: Registered distributions: Ubuntu,rancher-desktop-data,rancher-desktop
2023-12-08T19:31:09.088Z: data distro already registered
2023-12-08T19:31:16.162Z: Installing C:\Program Files\Rancher Desktop\resources\resources\linux\internal\trivy as /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/internal/trivy into /usr/local/bin/trivy ...
2023-12-08T19:31:16.787Z: Installing C:\Program Files\Rancher Desktop\resources\resources\linux\internal\rancher-desktop-guestagent as /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/internal/rancher-desktop-guestagent into /usr/local/bin//rancher-desktop-guestagent ...
2023-12-08T19:31:16.978Z: WSL: executing: cp /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/internal/trivy /usr/local/bin/trivy: Error: wsl.exe exited with code 1

2023-12-08T19:31:16.978Z: Error trying to cp C:\Program Files\Rancher Desktop\resources\resources\linux\internal\trivy as /mnt/c/Program Files/Rancher Desktop/resources/resources/linux/internal/trivy to /usr/local/bin/trivy: Error: wsl.exe exited with code 1


```

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/13620797/logs.zip)

### Expected Behavior

Rancher Desktop must restart with no errors

### Rancher Desktop Version

1.11.1-415-gec5adead

### Rancher Desktop K8s Version

1.27.7

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by ericpromislow** [comment]
I'm observing something interesting on macOS which might be related. I added a 2-minute delay `time.Sleep(120 * time.Second)` at the end of `manager.Create` and on 2/2 runs I get these startup errors on macOS:
```
limactl --debug start --tty=false 0 # ==>

errors inspecting instance: [failed to get Info from \\"/Users/ericp/Library/Application Support/rancher-desktop/lima/0/ha.sock\\": Get \\"http://lima-hostagent/v1/info\\": dial unix /Users/ericp/Library/Application Support/rancher-desktop/lima/0/ha.sock: connect: connection refused]
```

**Comment by ericpromislow** [comment]
Different error on Windows using a similar technique of stretching out the time needed to create a snapshot and holding the lock:
```
wsl --distribution rancher-desktop --exec /sbin/rc-update del dnsmasq-generate default
```
When run from powershell, I get this output:

```
>  wsl --distribution rancher-desktop --exec /sbin/rc-update del dnsmasq-generate default
 * rc-update: service `dnsmasq-generate' is not in the runlevel `default'
```

And this is another case where an error message running a `wsl` command doesn't get into any log file.

**Comment by mook-as** [comment]
I'm seeing yet a different issue, with the busy status JSON:
```
2023-12-09T01:18:12.270Z: UnhandledRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at zo (...\resources\app.asar\dist\app\background.js:41:134451)
    at async Yo (...\resources\app.asar\dist\app\background.js:41:134604)
    at async i.<anonymous> (...\resources\app.asar\dist\app\background.js:41:151255)
2023-12-09T01:18:12.270Z: Error starting up: SyntaxError: Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at zo (...\resources\app.asar\dist\app\background.js:41:134451)
    at async Yo (...\resources\app.asar\dist\app\background.js:41:134604)
    at async ...\resources\app.asar\dist\app\background.js:41:147180
    at async ...\resources\app.asar\dist\app\background.js:41:147153
```

**Comment by mook-as** [comment]
I can duplicate this now; with extra logging, I see:
> The virtual machine or container was forcefully exited.
> Error code: Wsl/Service/0x80370107

That code is `HCS_E_TERMINATED` which isn't too helpful.  I'll note though that other WSL distros are still running, so the machine itself is fine.

I think what's happening is:
- We start creating a snapshot
- Rancher Desktop starts, creating the backend HTTP server
- We complete the snapshot
- Simultaneously:
  - `rdctl` removes the lock file, causing the app to start the backend (because the polling no longer sees the lock file).
  - `rdctl` reads the HTTP configuration, sending a `PUT backend_state` to start the backend.
- The backend starts part way.
- The backend starts again, and runs `wsl --terminate rancher-desktop` as one of its steps.

**Comment by mook-as** [comment]
Yes, #5846 is a plausible result — we might end up starting twice, and the second start tries to import right after the first start finished importing.
