### ISSUE TITLE
rddepman CI job failing

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rancher-desktop#6635]
### Actual Behavior

It appears that the [rddepman](https://github.com/rancher-sandbox/rancher-desktop/blob/03c6412b7b26885ebf74ad3e7ac10b31a0ae8b61/.github/workflows/rddepman.yaml) CI job has been failing due to an issue with failing to create pull requests.

### Steps to Reproduce

Wait for the scheduled task to run, and fail to create PRs

### Result

```
> Run yarn rddepman
yarn run v1.22.22
$ node scripts/ts-wrapper.js scripts/rddepman.ts
kuberlr is up to date.
helm is up to date.
dockerCLI is up to date.
dockerBuildx is up to date.
dockerCompose is up to date.
dockerProvidedCredentialHelpers is up to date.
Can update trivy from "0.49.1" to "0.50.0"
guestAgent is up to date.
steve is up to date.
rancherDashboard is up to date.
ECRCredentialHelper is up to date.
lima is up to date.
limaAndQemu is up to date.
alpineLimaISO is up to date.
Can update WSLDistro from "0.56" to "0.57"
hostResolver is up to date.
wix is up to date.
Can update mobyOpenAPISpec from "1.44" to "1.45"
hostSwitch is up to date.
moproxy is up to date.
wasmShims is up to date.
Could not find PR "rddepman: bump trivy from 0.49.1 to 0.50.0". Will create.
Found existing PR "rddepman: bump WSLDistro from 0.56 to 0.57" (#6628).
Could not find PR "rddepman: bump mobyOpenAPISpec from 1.44 to 1.45". Will create.
Switched to a new branch 'rddepman/trivy/0.49.1-to-0.50.0'
[rddepman/trivy/0.49.1-to-0.50.0 857f0b56] Bump trivy from 0.49.1 to 0.50.0
 1 file changed, 1 insertion(+), 1 deletion(-)
To https://github.com/rancher-sandbox/rancher-desktop
 + 98ef3b53...857f0b56 rddepman/trivy/0.49.1-to-0.50.0 -> rddepman/trivy/0.49.1-to-0.50.0 (forced update)
Creating PR "rddepman: bump trivy from 0.49.1 to 0.50.0".
{"message":"At least one email address must be verified to do that.","documentation_url":"https://docs.github.com/articles/adding-an-email-address-to-your-github-account"}
RequestError [HttpError]: At least one email address must be verified to do that.
    at /home/runner/work/rancher-desktop/rancher-desktop/node_modules/@octokit/request/dist-node/index.js:112:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/rancher-desktop/rancher-desktop/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/home/runner/work/rancher-desktop/rancher-desktop/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/rancher-sandbox/rancher-desktop/pulls',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 21 Mar 2024 08:28:57 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': '',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '0400:245A45:EC772F:1A14DD9:65FBEFC8',
      'x-oauth-scopes': 'repo, workflow',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4570',
      'x-ratelimit-reset': '1711011835',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '430',
      'x-xss-protection': '0'
    },
    data: {
      message: 'At least one email address must be verified to do that.',
      documentation_url: 'https://docs.github.com/articles/adding-an-email-address-to-your-github-account'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/rancher-sandbox/rancher-desktop/pulls',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.1 octokit-core.js/5.0.1 Node.js/18.16.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"rddepman: bump trivy from 0.49.1 to 0.50.0","base":"main","head":"rddepman/trivy/0.49.1-to-0.50.0"}',
    request: { hook: [Function: bound bound register] }
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

The PR should be created successfully.

### Rancher Desktop Version

03c6412b7b26885ebf74ad3e7ac10b31a0ae8b61

### Rancher Desktop K8s Version

N/A

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

Ubuntu

### Operating System / Build Version

GitHub Actions

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by mook-as** [comment]
It magically works again, with no code changes from our side.
https://github.com/rancher-sandbox/rancher-desktop/actions/runs/8387500564/job/22969806032
