### ISSUE TITLE
docker-cli-monitor GHA fails to run

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7011]
The action has failed since May 1st with a `403`, but curiously worked on June 5th, but then failed again on June 6th: https://github.com/rancher-sandbox/rancher-desktop/actions/workflows/docker-cli-monitor.yaml

See also #7001.

The failure looks like this:

```
RequestError [HttpError]: Must have admin rights to Repository. - https://docs.github.com/rest/issues/issues#update-an-issue
    at /home/runner/work/rancher-desktop/rancher-desktop/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:125:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/rancher-desktop/rancher-desktop/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/home/runner/work/rancher-desktop/rancher-desktop/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/rancher-sandbox/rancher-desktop/issues/6776',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 06 Jun 2024 09:12:19 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': '',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '9080:6D188:1AC447A:2E14CF0:66617D73',
      'x-oauth-scopes': 'repo, workflow',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4832',
      'x-ratelimit-reset': '1717666415',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '168',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Must have admin rights to Repository.',
      documentation_url: 'https://docs.github.com/rest/issues/issues#update-an-issue'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/rancher-sandbox/rancher-desktop/issues/6776',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.2.1 octokit-core.js/5.2.0 Node.js/18.20.3 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"state":"closed"}',
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by mook-as** [comment]
The response contains the header:
> 'x-oauth-scopes': 'repo, workflow',

The [docs](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue) say we need `issues: write` or `pull_requests: write`; maybe the token just doesn't have the correct permissions? It's using the `RUN_WORKFLOW_FROM_WORKFLOW` secret, so we probably just need to let it take a separate token for closing PRs.

Also note that the error indicates it tried (and failed) to close #6776 which isn't a PR it should be touching; we probably need to tweak the filter.  Given that it was opened on Apr 25, perhaps that's why it failed previously (though it's unclear why it succeeded once).
