### ISSUE TITLE
containers/auto-start BATS test fails on macOS with 1.15.0 release build

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7337]
I'm pretty sure this worked for me in RC testing, but now fails repeatedly on both macOS Sonoma (Intel) and Sequoia Beta (Arm):

```
 ✗ Verify that the auto-start config is created
   (from function `assert_file_exists' in file bats-file/src/file.bash, line 72,
    in test file tests/containers/auto-start.bats, line 42)
     `assert_file_exists "$HOME/Library/LaunchAgents/io.rancherdesktop.autostart.plist"' failed

   -- file does not exist --
   path : /Users/jan/Library/LaunchAgents/io.rancherdesktop.autostart.plist
   --
```

Same thing happens when I set the autostart option manually via either `rdctl` or the preferences dialog: it never creates the autostart plist file.

**Comment by mook-as** [comment]
That test appears to have succeeded in https://github.com/rancher-sandbox/rancher-desktop/actions/runs/10316095503/job/28591674676, https://github.com/rancher-sandbox/rancher-desktop/actions/runs/10298581142/job/28504046163 and https://github.com/rancher-sandbox/rancher-desktop/actions/runs/10298581142/job/28504046990 (all failed later in the suite).

However, I can replicate the issue.

I think it's because my path management rewrite screwed up and threw an exception in `enforce()`, so it never got to the point where `runRdctlSetup()` was invoked:
https://github.com/rancher-sandbox/rancher-desktop/blob/1500fd557d7db8ebe7c3aa8e38572f126ca320d2/background.ts#L153-L165

```
2024-08-12T18:11:28.901Z: UnhandledRejectionWarning: Error: Refusing to manage …/.bashrc which has extended attributes
    at Kn (…/dist/app/background.js:41:63137)
    at async Promise.all (index 0)
    at async …/dist/app/background.js:41:65550
```

**Comment by mook-as** [comment]
Note that this was already fixed in #7297 (we catch any errors and report it instead of passing it up).

**Comment by mook-as** [comment]
Resolved with #7340 on `release-1.15`, and #7297 in `main`.
