### ISSUE TITLE
Failed to determine if `/Users/jan/.bash_profile` contains extended attributes

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop#7394]
This error happens on at least macOS Sonoma and Sequoia, and only in the signed and notarized release versions; not in regular CI builds.

The problem seems to be that `fs-xattr` contains native code compiled by `node-gyp` that is packaged into `app.asar` and therefore not codesigned as all the other bundled resources:

```
2024-08-29T21:29:52.193Z: Failed to import fs-xattr, cannot check for extended attributes on /Users/jan/.profile: Error: node-loader:
Error: dlopen(/var/folders/wm/pq6w7kf54215fxz392ff3rxr0000gn/T/.io.rancherdesktop.app.oxJtif, 0x0001): tried: '/var/folders/wm/pq6w7kf54215fxz392ff3rxr0000gn/T/.io.rancherdesktop.app.oxJtif' (code signature in <C0ADF24A-8E18-3804-B6A3-006BA059B42C> '/>
    at 5063 (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/12.js:1:671)
    at s (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:54148)
    at 9012 (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/12.js:1:85)
    at s (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:54148)
    at s.t (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:29:54365)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:162939
    at async g (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:162897)
    at async Bn.manageLinesInFile (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:61535)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:62173
2024-08-29T21:29:52.194Z: Error: Failed to determine if `/Users/jan/.profile` contains extended attributes
```

[Adding Unpacked Files to ASAR archives](https://www.electronjs.org/docs/latest/tutorial/asar-archives#adding-unpacked-files-to-asar-archives) explains how to keep `*.node` files unpacked, which seems better anyways, as they otherwise need to be written to `$TMPDIR` before they can be `require`d.

Let's try this and make sure all `*.node` files are also getting codesigned by `yarn sign ...`.

**Comment by klonos** [comment]
Sorry to be posting on a closed post, but this is a blocker for me. I see that there's a merged PR for this, however I'm unable to install RD on my freshly-installed MacBook provided by my employer. Is there any workaround to get it running while waiting for a new RD release that includes the fix? ...and also, any ETA on a new release?

Thanks in advance 🙏🏼

**Comment by jandubois** [comment]
> Is there any workaround

I think just selecting "Manual" path management and adding `$HOME/.rd/bin` to the `PATH` yourself in your shell profile should work around this issue.

> any ETA on a new release?

With luck next Thursday, or otherwise the following week.

**Comment by klonos** [comment]
Thanks for the very prompt reply @jandubois 🙏🏼

**Comment by nithaannarajan** [comment]
Even adding the path manually - I'm still getting the error.

**Comment by seymur-asadov** [comment]
For me, after switching to manual, and adding`$HOME/.rd/bin` to the `PATH` and restarting MacOS Sonoma worked.

**Comment by klonos** [comment]
FTR: I just upgraded to 1.16.0 and things were fixed for me.

**Comment by jandubois** [comment]
@klonos Thank you for confirming!
