### ISSUE TITLE
GuestAgent panics

### ISSUE THREAD

**Issue by Nino-K** [rancher-sandbox/rancher-desktop#7491]
Using this [commit](https://github.com/rancher-sandbox/rancher-desktop/commits/main/) for preliminary testing, I can see the following panic in the guest agent logs.

```
2024/09/16 15:41:31 [DEBUG]   received an event: /containers/update
panic: protobuf tag not enough fields in ContainerUpdate.state: 

goroutine 13 [running]:
github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc000442280)
	C:/Users/runneradmin/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:341 +0x1325
github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc000442280, {0x1e6fee0?}, {0xc00023a200, 0x1f3, 0x200})
	C:/Users/runneradmin/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:138 +0x5b
github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc000306700?, {0x226d4a8, 0xc0006145a0}, {0xc00023a200?, 0x1f3?, 0x200?})
	C:/Users/runneradmin/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/table_unmarshal.go:63 +0xc8
github.com/gogo/protobuf/proto.(*Buffer).Unmarshal(0xc0004d1d68, {0x226d4a8, 0xc0006145a0})
	C:/Users/runneradmin/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/decode.go:424 +0x165
github.com/gogo/protobuf/proto.Unmarshal({0xc00023a200, 0x1f3, 0x200}, {0x226d4a8, 0xc0006145a0})
	C:/Users/runneradmin/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/decode.go:342 +0x10a
github.com/rancher-sandbox/rancher-desktop/src/go/guestagent/pkg/containerd.(*EventMonitor).MonitorPorts(0xc00029c138, {0x227b940, 0xc00003c0a0})
	D:/a/rancher-desktop/rancher-desktop/src/go/guestagent/pkg/containerd/events.go:131 +0x996
main.main.func2()
	D:/a/rancher-desktop/rancher-desktop/src/go/guestagent/main.go:149 +0xdf
golang.org/x/sync/errgroup.(*Group).Go.func1()
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```

**Comment by Nino-K** [comment]
As suggested [here](https://github.com/containerd/ttrpc/issues/62), we have migrated from `github.com/gogo/protobuf` to `google.golang.org/protobuf`.
