### ISSUE TITLE
Rancher Desktop fails to start: X.509 certificate routines OPENSSL error on macOS Sequoia 15.2

### ISSUE THREAD

**Issue by dnddinesh22** [rancher-sandbox/rancher-desktop#7956]
### Actual Behavior

Rancher Desktop opens and immediately crashes on macOS Sequoia 15.2. Logs show an OpenSSL error (INVALID_FIELD_FOR_VERSION) related to X.509 certificate parsing.

### Steps to Reproduce

Install Rancher Desktop v1.16.0 - arm64 on macOS Sequoia 15.2.
Open Rancher Desktop.
Observe that the application opens briefly and then closes.

### Result

background.log Output:

rancher-desktop cat background.log 
2024-12-17T00:22:22.680Z: Error starting up: Error: error:0b00008b:X.509 certificate routines:OPENSSL_internal:INVALID_FIELD_FOR_VERSION Error: error:0b00008b:X.509 certificate routines:OPENSSL_internal:INVALID_FIELD_FOR_VERSION
    at new X509Certificate (node:internal/crypto/x509:119:21)
    at P (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:203425)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:208514
    at async te (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:208036)
    at async ee (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:206393)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:128316

networking.log Output:
cat networking.log 
...certificate verification successful.
...certificate verification successful.
2024-12-17T00:22:22.679Z: Error getting system certificates: Error: error:0b00008b:X.509 certificate routines:OPENSSL_internal:INVALID_FIELD_FOR_VERSION
    at new X509Certificate (node:internal/crypto/x509:119:21)
    at P (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:203425)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:208514
    at async te (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:208036)
    at async ee (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:2:206393)
    at async /Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:41:128316 {
  opensslErrorStack: [
    'error:0c00006d:ASN.1 encoding routines:OPENSSL_internal:DECODE_ERROR',
    'error:0900000c:PEM routines:OPENSSL_internal:ASN.1 encoding routines'
  ],
  library: 'X.509 certificate routines',
  function: 'OPENSSL_internal',
  reason: 'INVALID_FIELD_FOR_VERSION',
  code: 'ERR_OSSL_X509_INVALID_FIELD_FOR_VERSION'
}

### Expected Behavior

Rancher Desktop should start successfully without errors.

### Rancher Desktop Version

1.16.0

### Rancher Desktop K8s Version

Not sure

### Which container engine are you using?

containerd (nerdctl)

### What operating system are you using?

macOS

### Operating System / Build Version

MacOS - Apple M3 - macOS Sequoia 15.2 (24C101)

### What CPU architecture are you using?

arm64 (Apple Silicon)

### Linux only: what package format did you use to install Rancher Desktop?

None

**Comment by jandubois** [comment]
I agree that Rancher Desktop should handle this more gracefully, but I suspect you are behind some kind of MitM proxy server that intercepts all traffic, and that presents an invalid cert back to you.

Can you confirm that you are behind a proxy server?
