### ISSUE TITLE
macos 11.6: Right after start: FetchError: unable to get issuer certificate

### ISSUE THREAD

**Issue by roger-waldner** [rancher-sandbox/rancher-desktop#858]
**For bugs, describe what you're seeing**
Ranger Desktop v0.6.0 shows the above error message in a popup and in background.log
nerdctl reports Rancher Desktop as not running.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and install Rancher Desktop v0.6.0 for macOS (in my case: https://github.com/rancher-sandbox/rancher-desktop/releases/download/v0.6.0/Rancher.Desktop-0.6.0.dmg)
2. Start the freshly installed Rancher Desktop application

**Result**
A popup appears with the error message
Error Starting Kubernetes
There was an unknown error starting Kubernetes: FetchError: request to https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 failed, reason: unable to get issuer certificate

In the file background.log one finds the following entry:
```
Kubernetes was unable to start: FetchError: request to https://api.github.com/repos/k3s-io/k3s/releases?per_page=100 failed, reason: unable to get issuer certificate
    at ClientRequest.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'UNABLE_TO_GET_ISSUER_CERT',
  code: 'UNABLE_TO_GET_ISSUER_CERT'
}
```

**Expected behaviour**
No error message and a running Rancher Desktop application.

**Screenshots**
<img width="294" alt="ErrorRancherDesktop_v0 6 0" src="https://user-images.githubusercontent.com/70209223/138701662-e915b7eb-09d5-4701-817c-769c38ba08b6.png">

**Setup (please complete the following information):**
 - OS: macOS 11.6 (Big Sur)
 - Rancher Desktop version: v0.6.0

**Comment by roger-waldner** [comment]
I had the possibility to check Rancher Desktop on a second Mac with Big Sur. On that machine it works without problems. Seems to be a problem on my side.
