### ISSUE TITLE
[CI Windows] E2E Test failing due chrome crash

### ISSUE THREAD

**Issue by evertonlperes** [rancher-sandbox/rancher-desktop#942]
Need to investigate root cause for the following issue (only affect Windows runners):

Ref: https://github.com/rancher-sandbox/rancher-desktop/actions/runs/1443051823
```bash
FAIL e2e/main.e2e.spec.ts (60.374s)
  Rancher Desktop
    × opens the window (4ms)
    × should display welcome message in General tab (4ms)
    × should switch to Kubernetes Settings tab (2ms)
    × should switch to Port Forwarding tab (2ms)
    × should switch to Images tab (3ms)
    × should switch to Troubleshooting tab (1ms)
  console.log e2e/utils/TestUtils.ts:31
    Something went wrong during stop process.


  ● Rancher Desktop › opens the window

    Failed to create session.
    unknown error: Chrome failed to start: exited normally.
      (chrome not reachable)
      (The process started from chrome location D:\a\rancher-desktop\rancher-desktop\node_modules\spectron\lib\launcher.bat is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

      at Object.startWebDriverSession (node_modules/webdriver/build/utils.js:34:15)
      at Function.newSession (node_modules/webdriver/build/index.js:35:45)
      at Object.<anonymous>.exports.remote (node_modules/webdriverio/build/index.js:53:22)

  ● Rancher Desktop › opens the window

    TypeError: Cannot read property 'waitUntilWindowLoaded' of undefined

      34 |
      35 |   it('opens the window', async() => {
    > 36 |     await client.waitUntilWindowLoaded();
         |                  ^
      37 |     const title = await browserWindow.getTitle();
      38 |
      39 |     expect(title).toBe('Rancher Desktop');

      at Object.<anonymous> (e2e/main.e2e.spec.ts:36:18)

  ● Rancher Desktop › should display welcome message in General tab

    Failed to create session.
    unknown error: Chrome failed to start: exited normally.
      (chrome not reachable)
      (The process started from chrome location D:\a\rancher-desktop\rancher-desktop\node_modules\spectron\lib\launcher.bat is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

      at Object.startWebDriverSession (node_modules/webdriver/build/utils.js:34:15)
      at Function.newSession (node_modules/webdriver/build/index.js:35:45)
      at Object.<anonymous>.exports.remote (node_modules/webdriverio/build/index.js:53:22)

  ● Rancher Desktop › should display welcome message in General tab
```

**Comment by jandubois** [comment]
Expired
